import { PrismaClient } from "../../src/generated/prisma"
import { type FoodSeed } from "./types"

const foods: FoodSeed[] = [
  // ==================== MAIN DISHES (30) ====================
  {
    nameVi: "Cha ca La Vong",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suaát",
    servingGrams: 250,
    calories: 380,
    proteinG: 28,
    carbsG: 12,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Ca hoi cat mieng vua an, uop voi nghe, rieng, nuoc mam, tieu trong 20 phut",
      "Phi thom hanh tim, toi bam voi dau an tren chao gang",
      "Cho ca da uop vao chao, ap chao deu hai mat den khi vang gion",
      "Thi la va hanh la rua sach, thai khuc dai, cho vao chao dao nhanh cung ca",
      "Rac thi la tuoi, lac rang, vung rang len tren mat ca",
      "Bay ra dia, an kem bun va mam tom pha chanh ot",
      "Thuong thuc nong voi banh mi hoac bun tuoi",
    ],
    ingredients: [
      { ingredientName: "Ca hoi", grams: 150 },
      { ingredientName: "Bun", grams: 100 },
      { ingredientName: "Thi la", grams: 20 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nghe", grams: 5 },
      { ingredientName: "Rieng", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Lac", grams: 15 },
    ],
  },
  {
    nameVi: "Bun ca ro dong",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 to",
    servingGrams: 400,
    calories: 380,
    proteinG: 22,
    carbsG: 50,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Ca ro dong lam sach, danh vay, rua voi muoi va giam cho het nhot",
      "Ca ro chien vang deu hai mat tren chao dau nong",
      "Hanh tim, thi la bam nho phi thom voi dau an",
      "Cho ca vao noi, do nuoc xam xap, nem nuoc mam, muoi, bot nghe",
      "Nau soi roi ha lua nho, ham ca den khi ca chin mem",
      "Bun tuoi trung nuoc soi, xep ra to, chan nuoc dung va ca len tren",
      "Rac thi la, hanh la, tieu xay len mat va thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Ca ro", grams: 120 },
      { ingredientName: "Bun", grams: 200 },
      { ingredientName: "Thi la", grams: 15 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 12 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Muoi", grams: 3 },
      { ingredientName: "Nghe", grams: 3 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Mien xao cua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suaát",
    servingGrams: 300,
    calories: 340,
    proteinG: 18,
    carbsG: 42,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Mien ngam nuoc lanh 15 phut cho mem, cat khuc vua an",
      "Thit cua boc lay thit, xe nho, uop voi nuoc mam va tieu",
      "Phi thom hanh tim va toi bam voi dau an",
      "Cho thit cua vao xao san, them nam huong thai soi",
      "Cho mien vao chao, dao deu tay, nem nuoc mam va muoi",
      "Them gia do, hanh la, rau mui, dao nhanh roi tat bep",
      "Bay ra dia, rac tieu va an kem voi tuong ot",
    ],
    ingredients: [
      { ingredientName: "Mien", grams: 100 },
      { ingredientName: "Cua", grams: 80 },
      { ingredientName: "Gia do", grams: 50 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Nam", grams: 20 },
      { ingredientName: "Rau mui", grams: 5 },
    ],
  },
  {
    nameVi: "Com rang Bac",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 350,
    calories: 420,
    proteinG: 16,
    carbsG: 55,
    fatG: 15,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Com nguoi de rao, tach hat cho toi",
      "Trung ga danh tan, cho vao chao dau nong lam trung bong",
      "Phi thom hanh tim bam, cho com vao chao rang deu",
      "Nem nuoc mam, muoi, hat tieu, dao deu tay",
      "Them trung, dau Ha Lan, lap xuong thai hat lua vao rang cung",
      "Hanh la thai nho rac len com, tat bep",
      "Bay ra dia, an kem dua leo va nuoc tuong",
    ],
    ingredients: [
      { ingredientName: "Gao trang", grams: 200 },
      { ingredientName: "Trung ga", grams: 50 },
      { ingredientName: "Dau Ha Lan", grams: 30 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Dua leo", grams: 30 },
      { ingredientName: "Nuoc tuong", grams: 10 },
    ],
  },
  {
    nameVi: "Mi van than Ha Noi",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 to",
    servingGrams: 400,
    calories: 380,
    proteinG: 20,
    carbsG: 50,
    fatG: 12,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 25,
    difficulty: "hard",
    recipeSteps: [
      "Thit heo nac va tom bam nhuyen, tron voi nam meo, hanh tim bam",
      "Goi nhan vao banh van than thanh tung vien nho",
      "Ninh xuong heo voi hanh tay, gung, muoi de lay nuoc dung trong",
      "Luoc van than trong nuoc soi den khi noi len thi vot ra",
      "Mi trung nuoc soi, xep ra to cung van than va gia do",
      "Chan nuoc dung nong len tren, rac hanh la va rau mui",
      "Thuong thuc nong kem voi tuong ot va chanh",
    ],
    ingredients: [
      { ingredientName: "Mi", grams: 150 },
      { ingredientName: "Thit heo nac", grams: 50 },
      { ingredientName: "Tom", grams: 40 },
      { ingredientName: "Xuong heo", grams: 100 },
      { ingredientName: "Gia do", grams: 30 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Hanh tay", grams: 20 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
    ],
  },
  {
    nameVi: "Banh cuon nhan tom",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 250,
    calories: 300,
    proteinG: 14,
    carbsG: 40,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: "hard",
    recipeSteps: [
      "Pha bot gao voi nuoc loc, muoi, dau an, de nghi 20 phut",
      "Tom boc vo, bam nho cung thit heo nac, nem nuoc mam va tieu",
      "Phi thom hanh tim bam, xao nhan tom thit chin toi",
      "Trang banh tren xung hap, cho nhan vao giua, cuon lai",
      "Xep banh cuon ra dia, rac hanh phi va cha lua thai mong",
      "Pha nuoc mam chua ngot voi chanh, toi, ot, duong",
      "Rac rau mui va an kem voi gia do trung",
    ],
    ingredients: [
      { ingredientName: "Bot gao", grams: 100 },
      { ingredientName: "Tom", grams: 60 },
      { ingredientName: "Thit heo nac", grams: 40 },
      { ingredientName: "Hanh tim", grams: 15 },
      { ingredientName: "Cha lua", grams: 30 },
      { ingredientName: "Gia do", grams: 30 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Duong", grams: 5 },
    ],
  },
  {
    nameVi: "Chao ech",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 to",
    servingGrams: 350,
    calories: 320,
    proteinG: 18,
    carbsG: 42,
    fatG: 8,
    mealTime: ["breakfast", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Ech lam sach, loc lay thit, uop voi nuoc mam, gung, tieu",
      "Gao trang vo sach, cho vao noi ninh nhu thanh chao",
      "Phi thom hanh tim va toi bam voi dau an",
      "Xao thit ech san lai, nem gia vi vua an",
      "Cho thit ech vao noi chao, khua deu, nau them 10 phut",
      "Rac hanh la, rau mui, tieu xay len mat chao",
      "Muc ra to, thuong thuc nong voi quay hoac banh mi",
    ],
    ingredients: [
      { ingredientName: "Gao trang", grams: 80 },
      { ingredientName: "Ech", grams: 100 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Mi xao bo",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 350,
    calories: 420,
    proteinG: 22,
    carbsG: 48,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Mi trung trung nuoc soi, vot ra de rao",
      "Thit bo thai lat mong, uop voi nuoc tuong, dau an, tieu",
      "Phi thom toi bam voi dau an tren chao nong",
      "Xao bo tai, cho ra dia rieng",
      "Xao cai ngot va ca rot thai soi voi chut muoi",
      "Cho mi vao chao xao cung rau cu, nem nuoc tuong, them bo",
      "Bay ra dia, rac hanh la va tieu len mat",
    ],
    ingredients: [
      { ingredientName: "Mi", grams: 150 },
      { ingredientName: "Thit bo", grams: 80 },
      { ingredientName: "Cai ngot", grams: 50 },
      { ingredientName: "Ca rot", grams: 30 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc tuong", grams: 12 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Com ga Bac",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suat",
    servingGrams: 400,
    calories: 500,
    proteinG: 26,
    carbsG: 58,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Ga lam sach, cot chat de luoc cung gung, hanh tim va muoi",
      "Gao vo sach, nau com voi nuoc luoc ga cho thom",
      "Ga chin vot ra, de nguoi, chat mieng vua an",
      "Pha nuoc cham: nuoc mam, chanh, toi, ot, duong",
      "Xep com ra dia, dat thit ga len tren, rac hanh phi",
      "Rau mui, dua leo, ca chua thai lat trang tri ben canh",
      "Rac tieu xay va thuong thuc cung nuoc cham pha",
    ],
    ingredients: [
      { ingredientName: "Thit ga dui", grams: 150 },
      { ingredientName: "Gao trang", grams: 200 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Dua leo", grams: 30 },
      { ingredientName: "Ca chua", grams: 30 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Duong", grams: 5 },
    ],
  },
  {
    nameVi: "Thit bo xao can tay",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 280,
    proteinG: 26,
    carbsG: 8,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Thit bo thai lat mong ngang tho, uop voi nuoc tuong, dau an, tieu",
      "Can tay bo la, rua sach, cat khuc dai khoang 3 cm",
      "Ca rot thai lat mong, hanh tay thai mui cau",
      "Phi thom toi bam voi dau an tren chao nong",
      "Xao bo tren lua lon den khi chin tai, cho ra dia",
      "Xao can tay, ca rot, hanh tay chin toi, nem gia vi",
      "Cho bo vao dao deu, tat bep, bay ra dia",
    ],
    ingredients: [
      { ingredientName: "Thit bo", grams: 120 },
      { ingredientName: "Can tay", grams: 50 },
      { ingredientName: "Ca rot", grams: 30 },
      { ingredientName: "Hanh tay", grams: 30 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nuoc tuong", grams: 10 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Ga luoc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 250,
    calories: 320,
    proteinG: 30,
    carbsG: 3,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    difficulty: "easy",
    recipeSteps: [
      "Ga lam sach, xat muoi trong ngoai, rua lai voi nuoc",
      "Cho ga vao noi nuoc soi cung hanh tim, gung dap dap",
      "Luoc ga tren lua nho khoang 25 phut, thinh thoang tro mat",
      "Kiem tra do chin bang cach xiem que vao dui ga",
      "Vot ga ra tha vao thau nuoc da lanh de da gion",
      "Chat ga thanh mieng vua an, xep ra dia",
      "Pha muoi tieu chanh cham kem va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Thit ga dui", grams: 200 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Muoi", grams: 5 },
      { ingredientName: "Tieu", grams: 3 },
      { ingredientName: "Chanh", grams: 10 },
    ],
  },
  {
    nameVi: "Vit quay Bac",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 250,
    calories: 420,
    proteinG: 24,
    carbsG: 8,
    fatG: 32,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 40,
    cookTimeMinutes: 50,
    difficulty: "hard",
    recipeSteps: [
      "Vit lam sach, khu mui bang gung va muoi, rua sach de rao",
      "Pha hon hop uop: nuoc mam, ngu vi huong, mat ong, tieu, toi bam",
      "Uop vit voi hon hop gia vi trong 30 phut, tham deu ca trong ngoai",
      "Cho vit vao lo nuong o 180 do C, nuong 25 phut",
      "Quet lop mat ong len da vit, nuong them 15 phut cho da vang gion",
      "Lat vit, nuong deu cac mat den khi chin vang deu",
      "Chat vit mieng vua an, bay ra dia kem dua leo va rau mui",
    ],
    ingredients: [
      { ingredientName: "Thit vit", grams: 200 },
      { ingredientName: "Mat ong", grams: 20 },
      { ingredientName: "Nuoc mam", grams: 15 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Ngu vi huong", grams: 3 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Dua leo", grams: 30 },
      { ingredientName: "Rau mui", grams: 5 },
    ],
  },
  {
    nameVi: "Ca chep om dua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 250,
    calories: 320,
    proteinG: 28,
    carbsG: 10,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Ca chep lam sach, danh vay, cat khuc vua an",
      "Dua cai muoi rua so, vat bot nuoc chua, cat khuc",
      "Phi thom hanh tim va toi bam voi dau an",
      "Xep mot lop dua xuong noi, dat ca len tren, phu tiep lop dua",
      "Nem nuoc mam, muoi, tieu, gung thai soi, them nuoc xam xap",
      "Om ca tren lua nho 20 phut, them ot va hanh la",
      "Khi nuoc gan can, tat bep, bay ra dia va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Ca chep", grams: 150 },
      { ingredientName: "Dua cai muoi", grams: 50 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 12 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Ot", grams: 3 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Ca tram kho nghe",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 200,
    calories: 300,
    proteinG: 26,
    carbsG: 5,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Ca tram cat khuc, rua sach voi muoi, de rao",
      "Pha nuoc mau: dun duong voi dau an den khi co mau canh gian",
      "Phi thom hanh tim va toi bam voi nuoc mau",
      "Xep ca vao noi, do nuoc mam, muoi, bot nghe, nuoc xam xap",
      "Kho ca tren lua nho, them gung thai soi va ot",
      "Khi nuoc kho sat lai, rac hanh la va tieu",
      "Tat bep, bay ra dia, an kem com trang va rau song",
    ],
    ingredients: [
      { ingredientName: "Ca tram", grams: 150 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Nghe", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 12 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Duong", grams: 8 },
      { ingredientName: "Ot", grams: 3 },
    ],
  },
  {
    nameVi: "Thit dong",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 200,
    calories: 350,
    proteinG: 18,
    carbsG: 8,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 90,
    difficulty: "medium",
    recipeSteps: [
      "Thit heo ba chi va tai heo rua sach, luoc chin",
      "Thai thit va tai heo thanh mieng mong vua an",
      "Nam meo ngam no, thai soi. Ca rot thai lat mong",
      "Ninh xuong heo voi nuoc de lay nuoc dung dong",
      "Cho thit, tai heo, nam, ca rot vao noi nuoc dung, nem gia vi",
      "Do hon hop vao khuon, de nguoi roi cho vao ngan mat tu lanh",
      "Khi thit dong lai, lay ra thai mieng, an kem dua chua",
    ],
    ingredients: [
      { ingredientName: "Thit heo ba chi", grams: 100 },
      { ingredientName: "Tai heo", grams: 50 },
      { ingredientName: "Xuong heo", grams: 100 },
      { ingredientName: "Ca rot", grams: 20 },
      { ingredientName: "Nam", grams: 15 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Hanh tim", grams: 10 },
    ],
  },
  {
    nameVi: "Com chien trung",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 300,
    calories: 400,
    proteinG: 14,
    carbsG: 50,
    fatG: 16,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Com nguoi tach hat, de rao",
      "Trung ga dap ra bat, danh tan voi nuoc mam",
      "Hanh tim bam phi thom voi dau an",
      "Cho com vao chao, rang san, dao deu tay",
      "Do trung len com, dao nhanh cho trung bam deu hat com",
      "Nem nuoc mam, muoi, tieu, them hanh la thai nho",
      "Bay ra dia, dung nong voi tuong ot",
    ],
    ingredients: [
      { ingredientName: "Gao trang", grams: 200 },
      { ingredientName: "Trung ga", grams: 100 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Ga rang gung",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 350,
    proteinG: 28,
    carbsG: 6,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Thit ga dui chat mieng vua an, rua sach de rao",
      "Uop ga voi nuoc mam, muoi, tieu, gung thai soi trong 15 phut",
      "Ga chien so tren chao dau nong den khi vang mat",
      "Hanh tim bam phi thom, cho ga vao rang san",
      "Them nuoc mam, gung thai soi, dao deu",
      "Khi ga chin vang, rac hanh la va tieu",
      "Bay ra dia, an kem com nong",
    ],
    ingredients: [
      { ingredientName: "Thit ga dui", grams: 150 },
      { ingredientName: "Gung", grams: 15 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 12 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Muoi", grams: 2 },
    ],
  },
  {
    nameVi: "Thit lon nuong",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 380,
    proteinG: 22,
    carbsG: 10,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Thit heo ba chi thai mieng day vua, rua sach de rao",
      "Pha hon hop uop: nuoc mam, mat ong, dau an, toi bam, tieu",
      "Uop thit trong 25 phut, tham deu gia vi",
      "Xien thit vao que tre, nuong tren bep than hoac lo nuong",
      "Tro deu cac mat, quet them nuoc uop de thit khong kho",
      "Thit chin vang, thai mieng vua an, bay ra dia",
      "An kem dua leo, ca chua va nuoc cham chua ngot",
    ],
    ingredients: [
      { ingredientName: "Thit heo ba chi", grams: 150 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 12 },
      { ingredientName: "Mat ong", grams: 10 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Dua leo", grams: 30 },
      { ingredientName: "Ca chua", grams: 20 },
    ],
  },
  {
    nameVi: "Bo xao bong cai",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 250,
    calories: 300,
    proteinG: 26,
    carbsG: 10,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Thit bo thai lat mong, uop voi nuoc tuong, dau an, tieu",
      "Bong cai xanh cat mieng vua an, rua sach, chan so nuoc soi",
      "Ca rot thai lat, toi bam nho",
      "Phi thom toi voi dau an tren chao nong",
      "Xao bo chin tai, cho ra dia rieng",
      "Xao bong cai va ca rot chin toi, nem nuoc mam",
      "Cho bo vao dao deu, tat bep, bay ra dia",
    ],
    ingredients: [
      { ingredientName: "Thit bo", grams: 120 },
      { ingredientName: "Bong cai xanh", grams: 80 },
      { ingredientName: "Ca rot", grams: 30 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nuoc tuong", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Tom xao bong cai trang",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 240,
    proteinG: 24,
    carbsG: 8,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Tom boc vo, rut chi den, rua sach de rao",
      "Uop tom voi nuoc mam, tieu, toi bam",
      "Bong cai trang cat mieng vua an, chan so nuoc soi",
      "Phi thom toi bam voi dau an tren chao",
      "Xao tom chin hong, cho ra dia rieng",
      "Xao bong cai trang, nem gia vi vua an",
      "Cho tom vao dao deu, rac hanh la, tat bep",
    ],
    ingredients: [
      { ingredientName: "Tom", grams: 100 },
      { ingredientName: "Bong cai trang", grams: 80 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Lau ca chep",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 500,
    calories: 380,
    proteinG: 28,
    carbsG: 15,
    fatG: 22,
    mealTime: ["dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Ca chep lam sach, cat khuc, xat muoi cho het nhot",
      "Hanh tay, ca chua, thi la rua sach, thai mieng",
      "Phi thom hanh tim, sa bam voi dau an",
      "Cho ca chua vao xao nhuyen, do nuoc dung xuong heo",
      "Nem nuoc mam, me, duong, ot, muoi vua an",
      "Nuoc soi tha ca chep, nam, ca chua, thi la vao",
      "Rau song va bun an kem, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Ca chep", grams: 200 },
      { ingredientName: "Ca chua", grams: 50 },
      { ingredientName: "Hanh tay", grams: 30 },
      { ingredientName: "Sa", grams: 10 },
      { ingredientName: "Thi la", grams: 15 },
      { ingredientName: "Nam", grams: 30 },
      { ingredientName: "Nuoc mam", grams: 15 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Me", grams: 10 },
      { ingredientName: "Bun", grams: 150 },
    ],
  },
  {
    nameVi: "Lau ga me",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 500,
    calories: 360,
    proteinG: 26,
    carbsG: 18,
    fatG: 20,
    mealTime: ["dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Ga lam sach, chat mieng vua an, uop voi nuoc mam va tieu",
      "Me gia nhuyen, loc lay nuoc, bo ba",
      "Phi thom hanh tim, sa bam voi dau an",
      "Cho ga vao xao san, do nuoc me vao nau soi",
      "Nem nuoc mam, muoi, duong, ot vua an",
      "Them ca chua, nam, rau mong toi va rau ngot",
      "Don kem bun tuoi va rau song, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Thit ga dui", grams: 200 },
      { ingredientName: "Me", grams: 30 },
      { ingredientName: "Sa", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Ca chua", grams: 50 },
      { ingredientName: "Nam", grams: 30 },
      { ingredientName: "Mong toi", grams: 30 },
      { ingredientName: "Rau ngot", grams: 30 },
      { ingredientName: "Bun", grams: 150 },
      { ingredientName: "Nuoc mam", grams: 15 },
    ],
  },
  {
    nameVi: "Ca hoi ap chao",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 200,
    calories: 320,
    proteinG: 28,
    carbsG: 5,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    difficulty: "easy",
    recipeSteps: [
      "Ca hoi rua sach, tham kho, uop voi muoi, tieu, dau an",
      "Lam nong chao chong dinh voi chut dau an",
      "Dat ca hoi len chao, ap chao mat da truoc 4 phut",
      "Lat ca, ap chao mat kia 3 phut den khi chin vua",
      "Them bo va thi la len mat ca",
      "Vat chanh len ca, bay ra dia",
      "An kem khoai tay nghien hoac rau cu luoc",
    ],
    ingredients: [
      { ingredientName: "Ca hoi", grams: 150 },
      { ingredientName: "Thi la", grams: 10 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Muoi", grams: 2 },
      { ingredientName: "Tieu", grams: 2 },
      { ingredientName: "Khoai tay", grams: 50 },
    ],
  },
  {
    nameVi: "Muc xao chua ngot",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 260,
    proteinG: 24,
    carbsG: 12,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Muc lam sach, cat khoanh vua an, khua hoa",
      "Uop muc voi nuoc mam, tieu trong 10 phut",
      "Ca chua bo mui cau, hanh tay thai mieng",
      "Phi thom toi bam voi dau an",
      "Xao muc chin toi, cho ra dia rieng",
      "Xao ca chua, hanh tay, ot chuong, nem nuoc tuong, duong, giam",
      "Cho muc vao dao deu, tat bep, rac hanh la",
    ],
    ingredients: [
      { ingredientName: "Muc", grams: 120 },
      { ingredientName: "Ca chua", grams: 40 },
      { ingredientName: "Hanh tay", grams: 30 },
      { ingredientName: "Ot chuong", grams: 20 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Duong", grams: 8 },
      { ingredientName: "Giam", grams: 5 },
      { ingredientName: "Dau an", grams: 12 },
    ],
  },
  {
    nameVi: "Thit heo quay gion",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 200,
    calories: 420,
    proteinG: 20,
    carbsG: 5,
    fatG: 36,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 40,
    cookTimeMinutes: 50,
    difficulty: "hard",
    recipeSteps: [
      "Thit heo ba chi rua sach, luoc so, lau kho",
      "Dung dam tre xam deu len da heo",
      "Pha hon hop uop: nuoc mam, ngu vi huong, toi bam, tieu",
      "Thoa deu gia vi len thit, tru phan da, uop 30 phut",
      "Pha muoi va giam boi len da, de kho",
      "Nuong thit o 200 do C, lan dau 30 phut, tang len 220 do them 15 phut",
      "Da phong vang, thai mieng vua an, dung voi nuoc mam chua ngot",
    ],
    ingredients: [
      { ingredientName: "Thit heo ba chi", grams: 150 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Ngu vi huong", grams: 3 },
      { ingredientName: "Muoi", grams: 3 },
      { ingredientName: "Giam", grams: 5 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Bo nhung dam",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suat",
    servingGrams: 350,
    calories: 380,
    proteinG: 30,
    carbsG: 20,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Thit bo thai lat mong, xep ra dia",
      "Pha nuoc dung nhung: nuoc dua, giam, duong, muoi, sa, hanh tay",
      "Rau an kem: mong toi, rau ngot, cai thao, rau mui",
      "Bun xep ra dia rieng",
      "Dun soi noi nuoc dung tren bep lau",
      "Nhung thit bo vao noi dam soi, nhung tai vua chin",
      "Cuon bo voi rau song va bun, cham nuoc mam pha",
    ],
    ingredients: [
      { ingredientName: "Thit bo", grams: 150 },
      { ingredientName: "Bun", grams: 100 },
      { ingredientName: "Mong toi", grams: 30 },
      { ingredientName: "Cai thao", grams: 30 },
      { ingredientName: "Rau ngot", grams: 20 },
      { ingredientName: "Sa", grams: 10 },
      { ingredientName: "Dua", grams: 50 },
      { ingredientName: "Giam", grams: 15 },
      { ingredientName: "Hanh tay", grams: 30 },
      { ingredientName: "Nuoc mam", grams: 10 },
    ],
  },
  {
    nameVi: "Lau rieu cua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phan",
    servingGrams: 500,
    calories: 340,
    proteinG: 22,
    carbsG: 25,
    fatG: 16,
    mealTime: ["dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Cua dong xay nhuyen, loc lay nuoc cot, dun soi tao rieu",
      "Ca chua rua sach, thai mieng cau, xao nhuyen",
      "Phi thom hanh tim voi dau an, cho ca chua vao xao",
      "Do nuoc luoc xuong vao noi, them nuoc cua va rieu cua",
      "Nem nuoc mam, muoi, bot canh, me cho chua diu",
      "Tha doc mung, rau muong, hoa chuoi vao nhung",
      "Dung kem bun va mam tom, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Cua", grams: 150 },
      { ingredientName: "Ca chua", grams: 50 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Rau muong", grams: 50 },
      { ingredientName: "Bun", grams: 150 },
      { ingredientName: "Nuoc mam", grams: 15 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Me", grams: 15 },
      { ingredientName: "Mam tom", grams: 10 },
    ],
  },
  {
    nameVi: "Chao thit bam",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 to",
    servingGrams: 350,
    calories: 300,
    proteinG: 16,
    carbsG: 40,
    fatG: 8,
    mealTime: ["breakfast", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 30,
    difficulty: "easy",
    recipeSteps: [
      "Gao vo sach, cho vao noi ninh nhu voi nuoc",
      "Thit heo nac bam nhuyen, uop voi nuoc mam va tieu",
      "Phi thom hanh tim bam voi dau an",
      "Xao thit san lai, cho vao noi chao khua deu",
      "Them nuoc mam, muoi, hat nem vua an",
      "Rac hanh la, rau mui, tieu len mat chao",
      "Muc ra to, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Gao trang", grams: 80 },
      { ingredientName: "Thit heo nac", grams: 60 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Tieu", grams: 2 },
    ],
  },
  {
    nameVi: "Com nieu",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suat",
    servingGrams: 300,
    calories: 450,
    proteinG: 12,
    carbsG: 60,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Gao vo sach, ngam nuoc 20 phut cho no",
      "Cho gao vao nieu dat, them nuoc xam xap mat gao",
      "Day nap, dun tren bep lua nho den khi can nuoc",
      "Giam lua that nho, nuong nieu den khi com chin vang duoi day",
      "Rac hanh phi va mo hanh len mat com",
      "Dung kem ruoc, thit kho, ca kho",
      "Muc com ra bat, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Gao trang", grams: 200 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Hanh la", grams: 10 },
    ],
  },
  {
    nameVi: "Mi tron thit bam",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suat",
    servingGrams: 300,
    calories: 400,
    proteinG: 18,
    carbsG: 48,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    difficulty: "easy",
    recipeSteps: [
      "Mi luoc chin, vot ra de rao, tron voi chut dau an",
      "Thit heo nac bam nhuyen, uop voi nuoc mam va tieu",
      "Phi thom hanh tim va toi bam voi dau an",
      "Xao thit san lai, nem nuoc mam, duong, tuong ot",
      "Tron mi voi thit, them gia do trung, rau mui",
      "Rac hanh phi, lac rang gia dap len tren",
      "Bay ra dia, an kem do chua va ot",
    ],
    ingredients: [
      { ingredientName: "Mi", grams: 150 },
      { ingredientName: "Thit heo nac", grams: 80 },
      { ingredientName: "Gia do", grams: 30 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Lac", grams: 15 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Duong", grams: 5 },
    ],
  },
  // ==================== SIDE DISHES (15) ====================
  {
    nameVi: "Canh rau ngot thit bam",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bat",
    servingGrams: 250,
    calories: 100,
    proteinG: 8,
    carbsG: 8,
    fatG: 4,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    difficulty: "easy",
    recipeSteps: [
      "Rau ngot nhat la, rua sach, de rao",
      "Thit heo nac bam nhuyen, uop voi nuoc mam va tieu",
      "Phi thom hanh tim bam voi dau an",
      "Cho thit vao xao san, them nuoc soi vao noi",
      "Nem nuoc mam, muoi vua an",
      "Tha rau ngot vao, dun soi lai, tat bep",
      "Muc ra bat, rac tieu va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Rau ngot", grams: 100 },
      { ingredientName: "Thit heo nac", grams: 40 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Dau an", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
      { ingredientName: "Muoi", grams: 2 },
    ],
  },
  {
    nameVi: "Canh khoai mo",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bat",
    servingGrams: 250,
    calories: 120,
    proteinG: 3,
    carbsG: 22,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Khoai mo got vo, rua sach, thai mieng vua an",
      "Phi thom hanh tim bam voi dau an",
      "Cho khoai vao xao so, do nuoc xam xap",
      "Dun soi, ha lua nho nau den khi khoai chin mem",
      "Nem muoi, duong, hat nem vua an",
      "Rac hanh la va tieu len mat canh",
      "Muc ra bat, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Khoai mo", grams: 150 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Muoi", grams: 2 },
      { ingredientName: "Dau an", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Canh bau tom",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bat",
    servingGrams: 250,
    calories: 80,
    proteinG: 6,
    carbsG: 8,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bau got vo, rua sach, thai mieng mong vua an",
      "Tom boc vo, bam nho, uop voi nuoc mam va tieu",
      "Phi thom hanh tim voi dau an",
      "Xao tom san lai, do nuoc soi vao noi",
      "Tha bau vao nau chin mem",
      "Nem nuoc mam, muoi vua an",
      "Rac hanh la va tieu, muc ra bat",
    ],
    ingredients: [
      { ingredientName: "Bau", grams: 120 },
      { ingredientName: "Tom", grams: 40 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Dau an", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Canh cai ngot nau tom",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bat",
    servingGrams: 250,
    calories: 70,
    proteinG: 5,
    carbsG: 6,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Cai ngot rua sach, cat khuc vua an",
      "Tom boc vo, bam nho",
      "Phi thom hanh tim voi dau an",
      "Xao tom chin, them nuoc soi vao noi",
      "Nem nuoc mam va muoi vua an",
      "Tha cai ngot vao, dun soi lai, tat bep",
      "Rac tieu, muc ra bat thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Cai ngot", grams: 100 },
      { ingredientName: "Tom", grams: 30 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Dau an", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Nom bap cai",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 80,
    proteinG: 2,
    carbsG: 14,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Bap cai thai soi mong, rua sach, ngam nuoc muoi loang",
      "Ca rot bao soi, dua leo thai lat mong",
      "Pha nuoc tron: nuoc mam, duong, giam, toi bam, ot",
      "Vat rao bap cai, cho vao to cung ca rot va dua leo",
      "Ruoi nuoc tron len, dao deu",
      "Rac lac rang gia dap va rau mui len tren",
      "De tham 10 phut roi thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Bap cai", grams: 80 },
      { ingredientName: "Ca rot", grams: 30 },
      { ingredientName: "Dua leo", grams: 30 },
      { ingredientName: "Lac", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Duong", grams: 8 },
      { ingredientName: "Giam", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
      { ingredientName: "Rau mui", grams: 5 },
    ],
  },
  {
    nameVi: "Nom su hao ca rot",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 70,
    proteinG: 2,
    carbsG: 12,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Su hao got vo, thai soi mong",
      "Ca rot thai soi, ngam cung su hao voi nuoc muoi loang 10 phut",
      "Vat rao su hao va ca rot",
      "Pha nuoc tron: nuoc mam, duong, giam, toi, ot",
      "Tron deu rau cu voi nuoc tron",
      "Rac lac rang gia dap va rau mui len tren",
      "De tham 10 phut, an kem cac mon kho, ran",
    ],
    ingredients: [
      { ingredientName: "Su su", grams: 60 },
      { ingredientName: "Ca rot", grams: 50 },
      { ingredientName: "Lac", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Duong", grams: 8 },
      { ingredientName: "Giam", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
      { ingredientName: "Rau mui", grams: 5 },
    ],
  },
  {
    nameVi: "Rau cai luoc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 50,
    proteinG: 3,
    carbsG: 8,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Cai be xanh rua sach, cat khuc vua an",
      "Dun noi nuoc soi, cho chut muoi",
      "Tha rau cai vao luoc tren lua lon",
      "Khi rau chin toi, vot ra thau nuoc lanh",
      "Vot rau de rao, xep ra dia",
      "Pha nuoc mam cham kem voi toi, ot, chanh",
      "Dung kem com va cac mon man",
    ],
    ingredients: [
      { ingredientName: "Cai be xanh", grams: 150 },
      { ingredientName: "Muoi", grams: 3 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
      { ingredientName: "Chanh", grams: 5 },
    ],
  },
  {
    nameVi: "Dau phu ran",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 180,
    proteinG: 14,
    carbsG: 4,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Dau phu thai mieng vua an, de rao nuoc",
      "Lam nong dau an trong chao",
      "Xep dau phu vao chao ran vang deu cac mat",
      "Vot ra giay tham dau",
      "Pha nuoc mam cham: nuoc mam, chanh, toi, ot, duong",
      "Rau mui va dua leo xep ra dia kem dau",
      "Thuong thuc nong voi com",
    ],
    ingredients: [
      { ingredientName: "Dau phu", grams: 120 },
      { ingredientName: "Dau an", grams: 15 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
      { ingredientName: "Duong", grams: 3 },
    ],
  },
  {
    nameVi: "Dau phu sot ca chua",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 160,
    proteinG: 12,
    carbsG: 8,
    fatG: 10,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    difficulty: "easy",
    recipeSteps: [
      "Dau phu thai mieng, ran vang deu cac mat",
      "Ca chua rua sach, bam nho",
      "Phi thom hanh tim va toi bam voi dau an",
      "Cho ca chua vao xao nhuyen, nem nuoc mam, muoi, duong",
      "Them chut nuoc, dun soi thanh sot",
      "Cho dau phu ran vao noi sot, dun nho lua 5 phut",
      "Rac hanh la, tieu, bay ra dia",
    ],
    ingredients: [
      { ingredientName: "Dau phu", grams: 100 },
      { ingredientName: "Ca chua", grams: 60 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Duong", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Gia do xao",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 60,
    proteinG: 4,
    carbsG: 6,
    fatG: 3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Gia do rua sach, de rao",
      "Hanh la cat khuc, toi bam nho",
      "Lam nong chao voi dau an",
      "Phi thom toi bam",
      "Cho gia do vao xao tren lua lon, dao nhanh",
      "Nem nuoc mam, muoi, them hanh la",
      "Tat bep, bay ra dia, dung nong",
    ],
    ingredients: [
      { ingredientName: "Gia do", grams: 120 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Muoi", grams: 1 },
    ],
  },
  {
    nameVi: "Ca tim xao toi",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 80,
    proteinG: 2,
    carbsG: 8,
    fatG: 5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Ca tim rua sach, cat lat day vua, ngam nuoc muoi",
      "Vot ca ra de rao",
      "Phi thom toi bam voi dau an tren chao nong",
      "Xep ca vao chao, chien vang deu hai mat",
      "Nem nuoc mam, muoi, duong vua an",
      "Rac hanh la thai nho va tieu",
      "Bay ra dia, thuong thuc nong voi com",
    ],
    ingredients: [
      { ingredientName: "Ca tim", grams: 120 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 8 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Su su luoc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 40,
    proteinG: 2,
    carbsG: 8,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Su su got vo, bo ruot, thai mieng vua an",
      "Rua sach su su voi nuoc",
      "Dun noi nuoc soi, them chut muoi",
      "Tha su su vao luoc chin toi",
      "Vot ra dia, de rao",
      "Pha nuoc cham: nuoc mam, chanh, toi, ot",
      "Dung nong kem com va cac mon kho",
    ],
    ingredients: [
      { ingredientName: "Su su", grams: 150 },
      { ingredientName: "Muoi", grams: 2 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
    ],
  },
  {
    nameVi: "Bi xanh luoc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 35,
    proteinG: 1,
    carbsG: 7,
    fatG: 0.3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 7,
    difficulty: "easy",
    recipeSteps: [
      "Bi xanh got vo, bo ruot, thai mieng vua an",
      "Rua sach bi xanh",
      "Dun nuoc soi voi chut muoi",
      "Tha bi xanh vao luoc khoang 5 phut",
      "Vot bi ra dia, de rao nuoc",
      "Pha nuoc mam chanh toi ot cham kem",
      "Dung nong voi com",
    ],
    ingredients: [
      { ingredientName: "Bi xanh", grams: 150 },
      { ingredientName: "Muoi", grams: 2 },
      { ingredientName: "Nuoc mam", grams: 10 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Toi", grams: 3 },
      { ingredientName: "Ot", grams: 2 },
    ],
  },
  {
    nameVi: "Bong cai xanh luoc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 200,
    calories: 55,
    proteinG: 4,
    carbsG: 8,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 7,
    difficulty: "easy",
    recipeSteps: [
      "Bong cai xanh cat mieng vua an, rua sach",
      "Ngam nuoc muoi loang 5 phut, vot de rao",
      "Dun nuoc soi voi chut muoi va dau an",
      "Tha bong cai vao luoc 3 phut",
      "Vot ra thau nuoc da de giu mau xanh",
      "Vot ra dia, de rao",
      "Cham voi nuoc tuong hoac nuoc mam toi ot",
    ],
    ingredients: [
      { ingredientName: "Bong cai xanh", grams: 150 },
      { ingredientName: "Muoi", grams: 3 },
      { ingredientName: "Dau an", grams: 3 },
      { ingredientName: "Nuoc tuong", grams: 10 },
    ],
  },
  {
    nameVi: "Mang tay xao toi",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 60,
    proteinG: 3,
    carbsG: 6,
    fatG: 4,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Mang tay bo goc gia, rua sach, cat khuc",
      "Luoc mang tay so qua nuoc soi, vot de rao",
      "Toi bam nho, hanh la thai nho",
      "Lam nong dau an tren chao",
      "Phi thom toi bam",
      "Cho mang tay vao xao nhanh tren lua lon",
      "Nem nuoc mam, tieu, tat bep, bay ra dia",
    ],
    ingredients: [
      { ingredientName: "Mang tay", grams: 120 },
      { ingredientName: "Toi", grams: 5 },
      { ingredientName: "Hanh la", grams: 10 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  // ==================== SNACKS (15) ====================
  {
    nameVi: "Banh gio",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cai",
    servingGrams: 100,
    calories: 180,
    proteinG: 6,
    carbsG: 28,
    fatG: 6,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bot gao pha voi nuoc am, muoi, dau an, khua deu",
      "Nau hon hop bot tren lua nho den khi set",
      "Thit heo nac bam nhuyen cung nam meo, hanh tim, nem gia vi",
      "Xao nhan thit chin, them tieu va hanh kho phi",
      "Trai bot ra khan xo, cho nhan vao giua, goi lai",
      "Cho banh vao xung hap 15 phut",
      "Lay banh ra, de nguoi bot, dung kem nuoc mam chua ngot",
    ],
    ingredients: [
      { ingredientName: "Bot gao", grams: 60 },
      { ingredientName: "Thit heo nac", grams: 30 },
      { ingredientName: "Nam", grams: 10 },
      { ingredientName: "Hanh tim", grams: 10 },
      { ingredientName: "Dau an", grams: 8 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Banh san",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cai",
    servingGrams: 80,
    calories: 160,
    proteinG: 2,
    carbsG: 32,
    fatG: 3,
    mealTime: ["snack"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Khoai mi bao vo, ngam nuoc muoi loang, vat kho",
      "Tron khoai mi voi bot nang, duong, muoi, vung",
      "Nan hon hop thanh tung vien tron det",
      "Lam nhan: dau xanh hap chin, gia nhuyen voi duong",
      "Goi nhan vao giua banh, nan lai thanh hinh tron",
      "Xep banh vao xung hap chin khoang 15 phut",
      "Lay banh ra, rac vung rang, thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Khoai mi", grams: 60 },
      { ingredientName: "Dau xanh", grams: 15 },
      { ingredientName: "Duong", grams: 12 },
      { ingredientName: "Vung", grams: 5 },
      { ingredientName: "Dau an", grams: 5 },
    ],
  },
  {
    nameVi: "Banh khoai mon",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cai",
    servingGrams: 80,
    calories: 170,
    proteinG: 3,
    carbsG: 28,
    fatG: 6,
    mealTime: ["snack"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Khoai mon got vo, rua sach, bao soi",
      "Tom kho ngam no, bam nho",
      "Pha bot: bot gao, bot nang, nuoc, muoi, hanh la",
      "Tron khoai mon va tom kho vao hon hop bot",
      "Muc bot vao khuon, chien ngap dau den khi vang gion",
      "Vot banh ra giay tham dau",
      "Dung nong voi tuong ot",
    ],
    ingredients: [
      { ingredientName: "Khoai mon", grams: 50 },
      { ingredientName: "Bot gao", grams: 20 },
      { ingredientName: "Tom", grams: 10 },
      { ingredientName: "Hanh la", grams: 5 },
      { ingredientName: "Dau an", grams: 12 },
      { ingredientName: "Muoi", grams: 1 },
    ],
  },
  {
    nameVi: "Che ba cot",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bat",
    servingGrams: 200,
    calories: 220,
    proteinG: 4,
    carbsG: 42,
    fatG: 4,
    mealTime: ["snack"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Dau xanh ngam nuoc 2 gio, dai vo, hap chin",
      "Bot san day pha voi nuoc lanh, khua tan",
      "Dun nuoc soi, tha gung thai soi vao",
      "Tha bot san day vao noi, khua deu den khi trong",
      "Cho dau xanh vao noi che, them duong vua ngot",
      "Nuoc cot dua pha chut muoi, dun soi nhe",
      "Muc che ra bat, ruoi nuoc cot dua, rac vung",
    ],
    ingredients: [
      { ingredientName: "Dau xanh", grams: 40 },
      { ingredientName: "Bot san day", grams: 20 },
      { ingredientName: "Duong", grams: 30 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Dua", grams: 30 },
      { ingredientName: "Vung", grams: 5 },
    ],
  },
  {
    nameVi: "Che ngo",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bat",
    servingGrams: 250,
    calories: 230,
    proteinG: 5,
    carbsG: 45,
    fatG: 4,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    difficulty: "easy",
    recipeSteps: [
      "Ngo tuoi tach lay hat, rua sach",
      "Cho ngo vao noi nuoc, ninh nhu",
      "Dau xanh ngam nuoc, hap chin toi",
      "Khoai mo got vo, thai hat lua",
      "Cho dau xanh va khoai vao noi ngo, nau them 10 phut",
      "Them duong vua an, khua deu",
      "Muc ra bat, thuong thuc nong hoac lanh",
    ],
    ingredients: [
      { ingredientName: "Ngo", grams: 60 },
      { ingredientName: "Dau xanh", grams: 30 },
      { ingredientName: "Khoai mo", grams: 30 },
      { ingredientName: "Duong", grams: 25 },
    ],
  },
  {
    nameVi: "O mai mo",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phan",
    servingGrams: 50,
    calories: 110,
    proteinG: 1,
    carbsG: 24,
    fatG: 1,
    mealTime: ["snack"],
    prepTimeMinutes: 120,
    cookTimeMinutes: 30,
    difficulty: "hard",
    recipeSteps: [
      "Mo xanh rua sach, ngam nuoc muoi loang qua dem",
      "Mo vot ra, de rao, dung dao khua nhe",
      "Pha nuoc voi trong, ngam mo 4 gio cho het chua",
      "Xa mo nhieu lan nuoc sach, de rao",
      "Dun duong voi nuoc soi, cho mo vao rim lua nho",
      "Them gung thai soi, rim den khi mo trong va keo lai",
      "De nguoi, lan qua duong kinh bao quan trong lo",
    ],
    ingredients: [
      { ingredientName: "Mo", grams: 50 },
      { ingredientName: "Duong", grams: 35 },
      { ingredientName: "Gung", grams: 5 },
      { ingredientName: "Muoi", grams: 3 },
    ],
  },
  {
    nameVi: "Keo vung den",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phan",
    servingGrams: 50,
    calories: 240,
    proteinG: 6,
    carbsG: 28,
    fatG: 12,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Vung den rang chin thom",
      "Lac rang chin, bo vo, gia dap",
      "Dun duong voi nuoc va mach nha den khi set lai",
      "Tha vung den va lac vao noi duong, dao deu",
      "Do hon hop ra khay da phet dau an",
      "Dung can lan deu, thai mieng vua an khi con am",
      "De nguoi, bao quan trong hu kin",
    ],
    ingredients: [
      { ingredientName: "Vung", grams: 20 },
      { ingredientName: "Lac", grams: 15 },
      { ingredientName: "Duong", grams: 20 },
      { ingredientName: "Dau an", grams: 5 },
    ],
  },
  {
    nameVi: "Banh quai vac",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 suat",
    servingGrams: 100,
    calories: 200,
    proteinG: 6,
    carbsG: 28,
    fatG: 8,
    mealTime: ["snack"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bot gao nhao voi nuoc am, muoi, de nghi 20 phut",
      "Thit heo nac bam nhuyen, tron voi nam meo, hanh tim bam",
      "Nem nhan voi nuoc mam, tieu, muoi",
      "Can bot mong, cat hinh tron, cho nhan vao giua",
      "Gap doi bot, dung nan mep cho kin",
      "Hap banh 10 phut hoac chien vang",
      "Dung kem nuoc tuong pha toi ot",
    ],
    ingredients: [
      { ingredientName: "Bot gao", grams: 50 },
      { ingredientName: "Thit heo nac", grams: 30 },
      { ingredientName: "Nam", grams: 10 },
      { ingredientName: "Hanh tim", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Dau an", grams: 10 },
      { ingredientName: "Tieu", grams: 1 },
      { ingredientName: "Nuoc tuong", grams: 10 },
    ],
  },
  {
    nameVi: "Khoai tay chien",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 dia",
    servingGrams: 150,
    calories: 280,
    proteinG: 4,
    carbsG: 30,
    fatG: 16,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Khoai tay got vo, rua sach, thai soi hoac lat",
      "Ngam khoai tay trong nuoc muoi loang 10 phut",
      "Vot ra, tham kho hoan toan",
      "Lam nong dau an trong chao sau",
      "Chien khoai tay lua vua den khi vang gion",
      "Vot ra giay tham dau",
      "Rac muoi tieu hoac tuong ot va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Khoai tay", grams: 120 },
      { ingredientName: "Dau an", grams: 20 },
      { ingredientName: "Muoi", grams: 2 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Ngo nuong",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bap",
    servingGrams: 150,
    calories: 160,
    proteinG: 5,
    carbsG: 34,
    fatG: 2,
    mealTime: ["snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Ngo tuoi bo vo, giu lai lop vo trong cung",
      "Rua sach ngo, de rao",
      "Pha nuoc mam, dau an, tieu, ot bot",
      "Phet hon hop gia vi len bap ngo",
      "Nuong ngo tren bep than hong, tro deu",
      "Khi ngo chin vang thom, lay ra",
      "An nong kem muoi tieu chanh",
    ],
    ingredients: [
      { ingredientName: "Ngo", grams: 150 },
      { ingredientName: "Dau an", grams: 5 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Ot bot", grams: 2 },
      { ingredientName: "Tieu", grams: 1 },
    ],
  },
  {
    nameVi: "Khoai lang nuong",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cu",
    servingGrams: 150,
    calories: 140,
    proteinG: 2,
    carbsG: 32,
    fatG: 1,
    mealTime: ["snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 30,
    difficulty: "easy",
    recipeSteps: [
      "Khoai lang rua sach dat, de nguyen vo",
      "Lam nong lo nuong o 200 do C",
      "Xep khoai len khay nuong co lot giay bac",
      "Nuong khoai 25 phut, tro mat giua chung",
      "Kiem tra do chin bang cach xiem que",
      "Lay khoai ra, de hoi nguoi",
      "Be doi, thuong thuc khi con am",
    ],
    ingredients: [
      { ingredientName: "Khoai lang", grams: 150 },
    ],
  },
  {
    nameVi: "San luoc",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phan",
    servingGrams: 150,
    calories: 180,
    proteinG: 2,
    carbsG: 40,
    fatG: 1,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Khoai mi got vo, rua sach, cat khuc vua an",
      "Ngam khoai mi nuoc muoi loang 2 gio cho bot doc",
      "Rua lai nhieu lan nuoc sach",
      "Cho khoai vao noi, do nuoc xam xap, them chut muoi",
      "Luoc khoai tren lua vua den khi chin mem",
      "Vot khoai ra dia, de rao",
      "An kem muoi vung hoac duong",
    ],
    ingredients: [
      { ingredientName: "Khoai mi", grams: 150 },
      { ingredientName: "Muoi", grams: 3 },
    ],
  },
  {
    nameVi: "Banh mi que pate",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 suat",
    servingGrams: 100,
    calories: 260,
    proteinG: 10,
    carbsG: 28,
    fatG: 12,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 3,
    difficulty: "easy",
    recipeSteps: [
      "Banh mi que nuong gion tren bep than hoac lo nuong",
      "Phet pate gan len mat trong cua banh mi",
      "Dua leo thai lat mong, xep len pate",
      "Rau mui rua sach, xep len tren",
      "Tuong ot phet nhe len mat rau",
      "Kep banh mi lai, bay ra dia",
      "Thuong thuc nong, an kem xuc xich nuong",
    ],
    ingredients: [
      { ingredientName: "Banh mi", grams: 50 },
      { ingredientName: "Thit nguoi", grams: 20 },
      { ingredientName: "Dua leo", grams: 20 },
      { ingredientName: "Rau mui", grams: 5 },
      { ingredientName: "Tuong ot", grams: 5 },
    ],
  },
  {
    nameVi: "Banh trung nuong",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cai",
    servingGrams: 80,
    calories: 200,
    proteinG: 7,
    carbsG: 20,
    fatG: 10,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Trung ga danh tan voi nuoc mam, tieu, hanh la",
      "Thit heo nac thiam hat lua, xao so",
      "Pha bot mi voi nuoc, sua tuoi, trung tao thanh bot lot",
      "Tron thit, trung, nam, hanh tay vao bot",
      "Do hon hop vao khuon banh",
      "Nuong o 180 do C trong 15 phut",
      "Lay ra, de nguoi, cat mieng vua an",
    ],
    ingredients: [
      { ingredientName: "Bot mi", grams: 30 },
      { ingredientName: "Trung ga", grams: 50 },
      { ingredientName: "Thit heo nac", grams: 20 },
      { ingredientName: "Sua tuoi", grams: 20 },
      { ingredientName: "Hanh la", grams: 5 },
      { ingredientName: "Hanh tay", grams: 10 },
      { ingredientName: "Nam", grams: 10 },
      { ingredientName: "Nuoc mam", grams: 5 },
      { ingredientName: "Dau an", grams: 8 },
    ],
  },
  {
    nameVi: "Du du say",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phan",
    servingGrams: 50,
    calories: 130,
    proteinG: 1,
    carbsG: 30,
    fatG: 0.5,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 120,
    difficulty: "easy",
    recipeSteps: [
      "Du du chin got vo, ruot, thai lat mong dai",
      "Xep du du len khay, phoi nang 2-3 ngay",
      "Hoac say o 60 do C trong 6-8 gio",
      "Khi du du kho lai, dai deo la dat",
      "Bao quan trong lo kin",
      "Dung lam mon an vuat thuong thuc hang ngay",
      "Co the an kem chut muoi ot de tang huong vi",
    ],
    ingredients: [
      { ingredientName: "Du du", grams: 150 },
    ],
  },
  // ==================== DRINKS (10) ====================
  {
    nameVi: "Tra hoa nhai",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 5,
    proteinG: 0,
    carbsG: 1,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Tra xanh cho vao am, tram nuoc soi",
      "Do nuoc soi vao am, lat qua lat lai cho tra tham",
      "Bo tra ra, giu lai nuoc tra dac",
      "Hoa nhai kho cho vao am nuoc tra",
      "Dun nuoc soi de nguoi 80 do C, rot vao am",
      "Ham tra va hoa nhai trong 5 phut",
      "Rot ra ly, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Tra", grams: 5 },
    ],
  },
  {
    nameVi: "Sua chua uong",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 150,
    proteinG: 5,
    carbsG: 22,
    fatG: 5,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Sua chua cho vao binh to",
      "Them sua dac vao, khua deu",
      "Cho da vao ly",
      "Do hon hop sua chua vao ly",
      "Them chut duong neu thich",
      "Khuay deu va thuong thuc",
      "Co the them trai cay tuoi de tang huong vi",
    ],
    ingredients: [
      { ingredientName: "Sua chua", grams: 100 },
      { ingredientName: "Sua dac", grams: 30 },
      { ingredientName: "Duong", grams: 10 },
    ],
  },
  {
    nameVi: "Nuoc chanh muoi",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 60,
    proteinG: 0.2,
    carbsG: 14,
    fatG: 0,
    mealTime: ["snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Chanh muoi lay ra, cat lat mong",
      "Cho chanh muoi vao ly",
      "Them chut muoi va duong",
      "Cho da vao ly",
      "Do nuoc loc vao, khua deu",
      "Them la bac ha neu thich",
      "Thuong thuc mat lanh",
    ],
    ingredients: [
      { ingredientName: "Chanh", grams: 20 },
      { ingredientName: "Muoi", grams: 3 },
      { ingredientName: "Duong", grams: 15 },
      { ingredientName: "Bac ha", grams: 3 },
    ],
  },
  {
    nameVi: "Nuoc me",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 90,
    proteinG: 0.3,
    carbsG: 22,
    fatG: 0,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Me chin boc vo, rua sach",
      "Dun me voi nuoc soi trong 10 phut",
      "Danh tan me, loc lay nuoc cot, bo xac",
      "Them duong vao nuoc me, khua tan",
      "De nguoi hoac cho them da",
      "Co the them chut muoi de dam vi",
      "Rot ra ly, thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Me", grams: 30 },
      { ingredientName: "Duong", grams: 25 },
      { ingredientName: "Muoi", grams: 1 },
    ],
  },
  {
    nameVi: "Ca phe phin",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 150,
    calories: 5,
    proteinG: 0.5,
    carbsG: 0,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 1,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Cho ca phe xay vao phin, dan deu mat",
      "Rot nuoc soi vao phin, dong nap lai",
      "Cho phin len ly, de ca phe nho giot tu nhien",
      "Cho sua dac vao ly (neu uong ca phe sua)",
      "Cho da vao ly (neu uong ca phe da)",
      "Khuay deu ca phe voi sua/da",
      "Thuong thuc khi ca phe con thom",
    ],
    ingredients: [
      { ingredientName: "Ca phe", grams: 12 },
      { ingredientName: "Sua dac", grams: 20 },
    ],
  },
  {
    nameVi: "Nuoc rau ngo",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 60,
    proteinG: 1,
    carbsG: 14,
    fatG: 0,
    mealTime: ["snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Rau ngo tuoi boc vo, rua sach",
      "Cat rau ngo thanh khuc",
      "Cho rau ngo vao noi nuoc",
      "Dun soi roi ha lua nho, nau 15 phut",
      "Loc lay nuoc, bo xac",
      "Them duong vua ngot",
      "Uong nong hoac cho da de uong lanh",
    ],
    ingredients: [
      { ingredientName: "Ngo", grams: 50 },
      { ingredientName: "Duong", grams: 15 },
    ],
  },
  {
    nameVi: "Che xanh Thai Nguyen",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 3,
    proteinG: 0,
    carbsG: 0.5,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Che xanh Thai Nguyen cho vao am",
      "Tram am bang nuoc soi",
      "Rot nuoc soi vao am, lat deu cho tra tham",
      "Do bo nuoc tram di",
      "Rot nuoc soi lan hai vao am",
      "Ham tra 3 phut",
      "Rot ra tach, thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Tra", grams: 5 },
    ],
  },
  {
    nameVi: "Nuoc cam vat",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 100,
    proteinG: 1,
    carbsG: 22,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Cam rua sach, cat doi",
      "Vat lay nuoc cot, bo hat",
      "Cho duong vao nuoc cam, khua tan",
      "Cho da vao ly",
      "Do nuoc cam vao ly",
      "Trang tri voi lat cam thai mong",
      "Thuong thuc ngay de cam giu vi",
    ],
    ingredients: [
      { ingredientName: "Cam", grams: 200 },
      { ingredientName: "Duong", grams: 15 },
    ],
  },
  {
    nameVi: "Sinh to xoai",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 200,
    proteinG: 2,
    carbsG: 38,
    fatG: 6,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Xoai chin got vo, cat thit ra mieng",
      "Cho xoai vao may xay sinh to",
      "Them sua tuoi va sua dac",
      "Cho da vao may xay",
      "Xay nhuyen den khi min muot",
      "Rot ra ly",
      "Trang tri voi vai lat xoai thai mong",
    ],
    ingredients: [
      { ingredientName: "Xoai", grams: 150 },
      { ingredientName: "Sua tuoi", grams: 60 },
      { ingredientName: "Sua dac", grams: 20 },
    ],
  },
  {
    nameVi: "Sinh to du du",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 180,
    proteinG: 2,
    carbsG: 34,
    fatG: 5,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Du du chin got vo, bo ruot, cat mieng",
      "Cho du du vao may xay sinh to",
      "Them sua tuoi va sua dac",
      "Cho da vao may xay",
      "Xay nhuyen den khi min muot",
      "Rot ra ly",
      "Thuong thuc ngay de dam bao huong vi",
    ],
    ingredients: [
      { ingredientName: "Du du", grams: 150 },
      { ingredientName: "Sua tuoi", grams: 60 },
      { ingredientName: "Sua dac", grams: 20 },
    ],
  },
]

export async function seedFoodsMoreNorthern(prisma: PrismaClient) {
  const regions = await prisma.region.findMany()
  const categories = await prisma.category.findMany()
  const regionMap = Object.fromEntries(regions.map(r => [r.code, r.id]))
  const categoryMap = Object.fromEntries(categories.map(c => [c.slug, c.id]))

  for (const f of foods) {
    const foodData = {
      id: f.nameVi,
      nameVi: f.nameVi,
      servingSize: f.servingSize,
      servingGrams: f.servingGrams,
      calories: f.calories,
      proteinG: f.proteinG,
      carbsG: f.carbsG,
      fatG: f.fatG,
      mealTime: f.mealTime,
      recipeSteps: f.recipeSteps ?? [],
      prepTimeMinutes: f.prepTimeMinutes ?? null,
      cookTimeMinutes: f.cookTimeMinutes ?? null,
      difficulty: f.difficulty ?? null,
      isVerified: true,
      regionId: regionMap[f.regionCode],
      categoryId: categoryMap[f.categorySlug],
    }

    await prisma.food.upsert({
      where: { id: f.nameVi },
      update: foodData,
      create: {
        ...foodData,
        ingredients: {
          create: (f.ingredients ?? []).map(ing => ({
            ingredientName: ing.ingredientName,
            grams: ing.grams,
            proteinG: 0,
            carbsG: 0,
            fatG: 0,
          })),
        },
      },
    })
  }
  console.log(`✅ Seeded ${foods.length} northern dishes (more)`)
}
