import { PrismaClient } from "../../src/generated/prisma"
import { type FoodSeed } from "./types"

const foods: FoodSeed[] = [
  // ==================== MAIN DISHES (30) ====================
  {
    nameVi: "Mì Quảng bắp bò",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 420,
    proteinG: 26,
    carbsG: 48,
    fatG: 14,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit bo bap rua sach, luoc chin, thai lat mong",
      "Bước 2: Phi thom hanh tim va toi bam voi dau an",
      "Bước 3: Cho thit bo vao xao san, nem nuoc mam, tieu, duong",
      "Bước 4: Ninh xuong bo lay nuoc dung, them sa va gia vi",
      "Bước 5: Trung banh pho qua nuoc soi, cho ra to",
      "Bước 6: Xep thit bo, rau song len tren, chan nuoc dung",
      "Bước 7: Rac hanh la, rau mui, tieu xay va thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 150 },
      { ingredientName: "Bánh phở", grams: 200 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Mì Quảng cá lóc",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 24,
    carbsG: 46,
    fatG: 11,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ca loc lam sach, cat khuc vua an, uop gia vi",
      "Bước 2: Chien sa ca loc voi dau an cho vang deu",
      "Bước 3: Phi thom hanh tim, toi, sa bam",
      "Bước 4: Cho ca vao xao cung nghe bot va nuoc mam",
      "Bước 5: Ninh xuong heo lay nuoc dung, loc lay nuoc trong",
      "Bước 6: Banh pho trung nuoc soi, xep ra to, chan nuoc dung",
      "Bước 7: Xep ca len tren, rac rau thom, hanh la va tieu",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 150 },
      { ingredientName: "Bánh phở", grams: 200 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nghệ", grams: 3 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Mì Quảng vịt",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 400,
    proteinG: 22,
    carbsG: 45,
    fatG: 15,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit vit rua sach, luoc chin voi gung va muoi",
      "Bước 2: Xen thit vit, thai lat vua an",
      "Bước 3: Chien banh pho voi dau an cho thom",
      "Bước 4: Pha nuoc luoc vit voi gia vi, nem nuoc mam vua an",
      "Bước 5: Xep banh pho ra to, xep thit vit len tren",
      "Bước 6: Chan nuoc dung nong, rac hanh la, rau mui",
      "Bước 7: An kem voi rau song va chanh",
    ],
    ingredients: [
      { ingredientName: "Thịt vịt", grams: 150 },
      { ingredientName: "Bánh phở", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Gừng", grams: 5 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Mì Quảng chả lụa",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 380,
    calories: 360,
    proteinG: 18,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cha lua thai lat mong vua an",
      "Bước 2: Banh pho trung qua nuoc soi, de rao",
      "Bước 3: Hanh tim, toi bam phi thom voi dau an",
      "Bước 4: Cho cha lua vao xao so qua",
      "Bước 5: Trung banh pho bang nuoc dung xuong",
      "Bước 6: Xep banh pho ra to, xep cha lua len tren",
      "Bước 7: Rac lac rang, rau mui, hanh la va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Chả lụa", grams: 80 },
      { ingredientName: "Bánh phở", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Cao lầu thập cẩm",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 460,
    proteinG: 24,
    carbsG: 52,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Thit heo ba chỉ uop voi tieu, nuoc mam, toi bam 20 phut",
      "Bước 2: Tom rua sach, boc vo, uop gia vi",
      "Bước 3: Chien thit va tom voi dau an cho vang deu",
      "Bước 4: Mi xao so voi dau an va nuoc tuong",
      "Bước 5: Xep mi ra to, xep thit va tom len tren",
      "Bước 6: Chan nuoc dung xuong heo nong, rac rau song",
      "Bước 7: Rac hanh phi, lac rang, an kem voi chanh",
    ],
    ingredients: [
      { ingredientName: "Thịt heo ba chỉ", grams: 100 },
      { ingredientName: "Tôm", grams: 80 },
      { ingredientName: "Mì", grams: 150 },
      { ingredientName: "Dầu ăn", grams: 12 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Nước tương", grams: 8 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bánh canh bột lọc giò",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 16,
    carbsG: 55,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Giò thai lat mong vua an",
      "Bước 2: Ninh xuong heo voi hanh tay de lay nuoc dung",
      "Bước 3: Banh canh bot loc trung nuoc soi, vot ra",
      "Bước 4: Phi thom hanh tim, cho gio vao xao so",
      "Bước 5: Xep banh canh ra to, xep gio len tren",
      "Bước 6: Chan nuoc dung nong len tren",
      "Bước 7: Rac hanh la, tieu xay va thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Giò", grams: 80 },
      { ingredientName: "Bột gạo", grams: 100 },
      { ingredientName: "Hành tây", grams: 20 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bánh canh sườn",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 420,
    proteinG: 20,
    carbsG: 55,
    fatG: 12,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Suon non chặt miếng vua an, rửa sach, đe rao",
      "Bước 2: Uop suon voi nuoc mam, tieu, toi bam 15 phut",
      "Bước 3: Chien suon voi dau an cho vang đeu",
      "Bước 4: Ninh suon voi nuoc, them gia vi vao",
      "Bước 5: Banh canh trung nuoc soi, cho ra to",
      "Bước 6: Chan nuoc suon len tren, xep suon ra mat",
      "Bước 7: Rac hanh la, tieu xay va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Thịt heo nạc", grams: 100 },
      { ingredientName: "Bột gạo", grams: 100 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Gia vị", grams: 5 },
    ],
  },
  {
    nameVi: "Bún bò giò",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 450,
    proteinG: 28,
    carbsG: 50,
    fatG: 16,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 90,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Thit bo bap va gio heo rua sach, luoc so",
      "Bước 2: Ninh xuong bo voi sa, hanh tay, muoi trong 60 phut",
      "Bước 3: Thit bo thai lat mong, gio heo thai khoanh",
      "Bước 4: Bun trung nuoc soi, xep ra to",
      "Bước 5: Xep thit bo va gio heo len tren bun",
      "Bước 6: Chan nuoc dung nong, them ot beo",
      "Bước 7: Rac hanh la, rau mui, tieu xay len mat",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 100 },
      { ingredientName: "Giò", grams: 50 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Hành tây", grams: 20 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bún cá thu",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 24,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ca thu lam sach, cat khuc, uop voi muoi va nghe",
      "Bước 2: Chien ca thu voi dau an cho vang đeu",
      "Bước 3: Phi thom hanh tim, toi, sa bam voi dau an",
      "Bước 4: Cho ca thu vao xao cung nuoc mam va gia vi",
      "Bước 5: Bun trung nuoc soi, cho ra to",
      "Bước 6: Xep ca thu len bun, chan nuoc dung nong",
      "Bước 7: Rac hanh la, thi la va tieu xay",
    ],
    ingredients: [
      { ingredientName: "Cá thu", grams: 120 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Thì là", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bún sườn non",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 420,
    proteinG: 22,
    carbsG: 52,
    fatG: 14,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Suon non rua sach, chat khuc vua an, đe rao",
      "Bước 2: Uop suon voi nuoc mam, tieu, duong, toi bam 15 phut",
      "Bước 3: Chien suon voi dau an cho vang đeu hai mat",
      "Bước 4: Cho suon vao noi, đo nuoc xam xap, ham chin",
      "Bước 5: Bun trung nuoc soi, xep ra to",
      "Bước 6: Chan nuoc suon len bun, xep suon ra tren",
      "Bước 7: Rac hanh la, rau mui, tieu xay len mat",
    ],
    ingredients: [
      { ingredientName: "Thịt heo nạc", grams: 120 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bún riêu cua",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 380,
    proteinG: 20,
    carbsG: 50,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Cua đồng lam sạch, tách lấy thịt và mai",
      "Bước 2: Giat cua lay nuoc, loc lay nuoc trong",
      "Bước 3: Trung ga đanh tan, cho vao nuoc cua khuay đeu",
      "Bước 4: Đun nuoc cua lua nho đen khi riêu noi len",
      "Bước 5: Ca chua thai mieng, xao voi hanh tim cho chin",
      "Bước 6: Bun trung nuoc soi, xep ra to, chan nuoc riêu",
      "Bước 7: Them riêu, rau song, hanh la va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Cua", grams: 100 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Trứng gà", grams: 30 },
      { ingredientName: "Cà chua", grams: 50 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 10 },
    ],
  },
  {
    nameVi: "Bún mắm",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 500,
    calories: 450,
    proteinG: 22,
    carbsG: 55,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Tom, muc lam sach, cat vua an",
      "Bước 2: Thit heo ba chỉ thai mieng mong",
      "Bước 3: Phi thom hanh tim, toi, sa voi dau an",
      "Bước 4: Cho thit va hai san vao xao san",
      "Bước 5: Pha man tom voi nuoc, loc lay nuoc trong",
      "Bước 6: Bun trung nuoc soi, xep ra to",
      "Bước 7: Chan nuoc man, xep thit, tom, muc len tren",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 50 },
      { ingredientName: "Mực", grams: 50 },
      { ingredientName: "Thịt heo ba chỉ", grams: 80 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Mắm tôm", grams: 20 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
    ],
  },
  {
    nameVi: "Cơm gà xé phay",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 400,
    calories: 520,
    proteinG: 28,
    carbsG: 60,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit ga đùi rửa sạch, luộc chín với gừng",
      "Bước 2: Xé thit ga thành sợi nhỏ vừa ăn",
      "Bước 3: Pha nước mắm trộn với chanh, đường, ớt",
      "Bước 4: Trộn thit ga xé với hành tây thái mỏng",
      "Bước 5: Nấu cơm trắng voi gao trắng",
      "Bước 6: Xep cơm ra dĩa, xếp thit ga xé lên trên",
      "Bước 7: Rắc rau mùi, lạc rang và thưởng thức",
    ],
    ingredients: [
      { ingredientName: "Thịt gà đùi", grams: 150 },
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Hành tây", grams: 30 },
      { ingredientName: "Chanh", grams: 15 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Gừng", grams: 5 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Rau mùi", grams: 5 },
    ],
  },
  {
    nameVi: "Cơm sườn bì",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 450,
    calories: 580,
    proteinG: 28,
    carbsG: 72,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Suon non uop voi nuoc mam, tieu, toi, duong 20 phut",
      "Bước 2: Nuong suon tren than hoa hoac chien vang",
      "Bước 3: Thit heo nac luoc chin, xe nho tron voi bì",
      "Bước 4: Pha cheo voi duong, nuoc mam, giam, ot",
      "Bước 5: Nan cơm ra dĩa, xep suon va bì ben canh",
      "Bước 6: Them rau dưa leo, ca chua trang tri",
      "Bước 7: Chan nước mắm pha len suon va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Thịt heo nạc", grams: 150 },
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Dưa leo", grams: 30 },
      { ingredientName: "Cà chua", grams: 30 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Đường", grams: 8 },
      { ingredientName: "Giấm", grams: 5 },
      { ingredientName: "Ớt", grams: 5 },
    ],
  },
  {
    nameVi: "Cơm bò xào",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 400,
    calories: 550,
    proteinG: 30,
    carbsG: 58,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Thit bo thai lat mong, uop voi toi, tieu, nuoc mam",
      "Bước 2: Phi thom hanh tay voi dau an",
      "Bước 3: Cho thit bo vao xao lua lon cho chin tai",
      "Bước 4: Nan cơm trắng ra dĩa",
      "Bước 5: Xep thit bo xao len tren cơm",
      "Bước 6: Them dưa leo, ca chua cat lat",
      "Bước 7: Rac hanh la va thuong thuc nong",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 150 },
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Hành tây", grams: 30 },
      { ingredientName: "Dầu ăn", grams: 12 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Dưa leo", grams: 30 },
      { ingredientName: "Cà chua", grams: 20 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Cơm chiên dương châu",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 350,
    calories: 450,
    proteinG: 16,
    carbsG: 55,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cơm nguoi đe rao, tach hat cho toi",
      "Bước 2: Thit heo nac, tom thai hat lua",
      "Bước 3: Phi thom hanh tay bam voi dau an",
      "Bước 4: Cho thit va tom vao xao san",
      "Bước 5: Cho cơm vao chao, rang đeu tay",
      "Bước 6: Nem nuoc mam, muoi, tieu, trung ga vao dao đeu",
      "Bước 7: Hanh la thai nho rac len, tat bep va xuong dĩa",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Thịt heo nạc", grams: 50 },
      { ingredientName: "Tôm", grams: 40 },
      { ingredientName: "Trứng gà", grams: 30 },
      { ingredientName: "Hành tây", grams: 20 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Cơm niêu",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 niêu",
    servingGrams: 350,
    calories: 480,
    proteinG: 12,
    carbsG: 65,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Gao trắng vo sạch, ngâm nước 30 phut",
      "Bước 2: Cho gao vao niêu đat, the nuoc vua phai",
      "Bước 3: Nấu tren bep lua nho đen chin",
      "Bước 4: Khi cơm gan chin, tiet lua nho de tao chay",
      "Bước 5: Lật niêu đe cơm chay đeu đay",
      "Bước 6: Dung cơm niêu voi muoi vung hoac kho quet",
      "Bước 7: Hat phan chay gion ra, an nong",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 250 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Vừng", grams: 5 },
      { ingredientName: "Mè rang", grams: 5 },
      { ingredientName: "Dầu olive", grams: 5 },
    ],
  },
  {
    nameVi: "Cơm cháy kho quẹt",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 380,
    proteinG: 10,
    carbsG: 50,
    fatG: 16,
    mealTime: ["snack", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Lấy phan cơm chay tu niêu, đe ngui",
      "Bước 2: Chien cơm chay voi dau an cho gion",
      "Bước 3: Thit heo ba chỉ thai hat lua, rang cho ra bot",
      "Bước 4: Cho nuoc mam, đuong, tieu vao, khuay đeu",
      "Bước 5: Nho lua, nấu cho đen khi keo sanh lai",
      "Bước 6: Bay cơm chay ra dĩa, chan kho quet len tren",
      "Bước 7: Them tieu xay, an nong",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 150 },
      { ingredientName: "Thịt heo ba chỉ", grams: 50 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Đường", grams: 20 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Tiêu", grams: 3 },
    ],
  },
  {
    nameVi: "Bò xào sả ớt",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 250,
    calories: 320,
    proteinG: 28,
    carbsG: 8,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Thit bo thai lat mong, uop voi tieu, nuoc mam",
      "Bước 2: Sa bam nho, ot thai lat",
      "Bước 3: Phi thom sa, toi bam voi dau an",
      "Bước 4: Cho thit bo vao xao lua lon",
      "Bước 5: Nem them nuoc mam, đuong vao",
      "Bước 6: Cho ot vao đao đeu, tat bep",
      "Bước 7: Bay ra dĩa, rac tieu xay, an com nong",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 150 },
      { ingredientName: "Sả", grams: 15 },
      { ingredientName: "Ớt", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bò nướng than hoa",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 340,
    proteinG: 28,
    carbsG: 5,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit bo thai lat mong vua an",
      "Bước 2: Uop bo voi toi, sa, nuoc mam, tieu, mat ong 20 phut",
      "Bước 3: Xiên thit bo vao que tre",
      "Bước 4: Nuong tren bep than hoa đen chin vang",
      "Bước 5: Pha nuoc cham cheo voi nuoc mam, chanh, ot",
      "Bước 6: Bay thit bo nuong ra dĩa",
      "Bước 7: An kem voi rau song va bun",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 150 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Mật ong", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Bún", grams: 100 },
    ],
  },
  {
    nameVi: "Gà xào gừng",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 250,
    calories: 300,
    proteinG: 26,
    carbsG: 6,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Thit ga đùi rửa sạch, thái miếng vừa an",
      "Bước 2: Gừng gọt vỏ, thái sợi",
      "Bước 3: Uop ga voi nuoc mam, tieu, gung 15 phut",
      "Bước 4: Phi thom hanh tim bam voi dau an",
      "Bước 5: Cho ga vao xao chin đeu",
      "Bước 6: Them so gung con lai, đao đeu, tat bep",
      "Bước 7: Bay ra dĩa, rac tieu xay",
    ],
    ingredients: [
      { ingredientName: "Thịt gà đùi", grams: 150 },
      { ingredientName: "Gừng", grams: 20 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Gà nướng riềng mẻ",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 360,
    proteinG: 28,
    carbsG: 8,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 40,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit ga đùi rửa sạch, để rao",
      "Bước 2: Riềng, sả, tỏi, ớt băm nhuyễn",
      "Bước 3: Pha nuoc mam, mật ong, tieu, bột riềng",
      "Bước 4: Uop ga voi hỗn hợp gia vi trong 30 phut",
      "Bước 5: Nuong ga tren bep than hoa đen chin vang",
      "Bước 6: Trở đeu đe ga chin đều hai măt",
      "Bước 7: Bay ra dĩa, an kem voi cơm nong",
    ],
    ingredients: [
      { ingredientName: "Thịt gà đùi", grams: 200 },
      { ingredientName: "Riềng", grams: 15 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Mật ong", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Vịt om sấu",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 300,
    calories: 350,
    proteinG: 24,
    carbsG: 10,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 45,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit vit rửa sạch, thái miếng vừa an",
      "Bước 2: Uop vit voi gung, nuoc mam, tieu 15 phut",
      "Bước 3: Phi thom hanh tay, toi, sa bam voi dau an",
      "Bước 4: Cho vit vao xao san",
      "Bước 5: Đo nuoc du, om lua nho đen vit chin mem",
      "Bước 6: Nem nuoc mam, muoi vua an",
      "Bước 7: Rac hanh la, rau mui, tieu xay len mat",
    ],
    ingredients: [
      { ingredientName: "Thịt vịt", grams: 200 },
      { ingredientName: "Gừng", grams: 10 },
      { ingredientName: "Hành tây", grams: 30 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Sả", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Vịt kho gừng",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 380,
    proteinG: 26,
    carbsG: 8,
    fatG: 26,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit vit thai mieng vua an, rua sach",
      "Bước 2: Uop vit voi nuoc mam, gung, tieu 15 phut",
      "Bước 3: Phi thom hanh tim voi dau an",
      "Bước 4: Cho vit vao kho lua nho",
      "Bước 5: Them gung thai soi, duong, nuoc mau",
      "Bước 6: Kho đen khi nuoc can, thit vit chin mem, bong",
      "Bước 7: Bay ra dĩa, rac tieu xay, an kem com nong",
    ],
    ingredients: [
      { ingredientName: "Thịt vịt", grams: 200 },
      { ingredientName: "Gừng", grams: 20 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 12 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Cá lóc kho tộ",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 280,
    proteinG: 28,
    carbsG: 4,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ca loc lam sach, cat khoanh vua an",
      "Bước 2: Uop ca voi nuoc mam, tieu, ot, toi bam 15 phut",
      "Bước 3: Phi thom hanh tim, toi trong to đat",
      "Bước 4: Xep ca vao to, chan nuoc uop",
      "Bước 5: Kho lua nho đen ca chin, nuoc hoi sanh",
      "Bước 6: Them tieu xay, ot thai lat",
      "Bước 7: Tat bep, bay ra, an kem com nong",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 150 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Đường", grams: 8 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Dầu ăn", grams: 8 },
    ],
  },
  {
    nameVi: "Cá basa kho tộ",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 320,
    proteinG: 24,
    carbsG: 4,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ca basa lam sach, cat khoanh 3 cm",
      "Bước 2: Uop ca voi nuoc mam, tieu, toi, duong 15 phut",
      "Bước 3: Phi thom hanh tim bam trong to đat",
      "Bước 4: Xep ca vao to, cho nuoc uop vao",
      "Bước 5: Kho tren bep lua nho đen nuoc can, ca chin",
      "Bước 6: Them tieu xay, ot thai lat",
      "Bước 7: Dung com nong kem ca kho",
    ],
    ingredients: [
      { ingredientName: "Cá basa", grams: 150 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 8 },
    ],
  },
  {
    nameVi: "Cá thu sốt cà chua",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 300,
    proteinG: 26,
    carbsG: 6,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ca thu lam sach, cat khoanh, uop muoi",
      "Bước 2: Chien ca thu voi dau an cho vang",
      "Bước 3: Ca chua thai mieng, xao voi hanh tim",
      "Bước 4: Cho ca thu vao noi, đo nuoc xam xap",
      "Bước 5: Sot lua nho đen tham gia vi",
      "Bước 6: Nem nuoc mam, duong vua an",
      "Bước 7: Rac hanh la, tieu xay len mat",
    ],
    ingredients: [
      { ingredientName: "Cá thu", grams: 150 },
      { ingredientName: "Cà chua", grams: 80 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Muối", grams: 3 },
    ],
  },
  {
    nameVi: "Tôm rang thịt ba chỉ",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 340,
    proteinG: 24,
    carbsG: 6,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Tom rua sach, cat bo đau, đe rao",
      "Bước 2: Thit heo ba chỉ thai mirng moi vua an",
      "Bước 3: Rang thit heo voi lua nho đen ra mơ",
      "Bước 4: Cho tom vao rang cung thit",
      "Bước 5: Nem nuoc mam, tieu, duong vao",
      "Bước 6: Xao đeu đen khi tom chin, thit vang",
      "Bước 7: Bay ra dĩa, rac hanh la va thuong thuc",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 100 },
      { ingredientName: "Thịt heo ba chỉ", grams: 80 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Tép rang",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 280,
    proteinG: 22,
    carbsG: 5,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Tep rua sach, đe rao",
      "Bước 2: Phi thom hanh tim bam voi dau an",
      "Bước 3: Cho tep vao rang lua nho",
      "Bước 4: Nem nuoc mam, tiế, đuong vào",
      "Bước 5: Rang đen khi tep gion, vang đeu",
      "Bước 6: Bay ra dĩa, an com nong",
    ],
    ingredients: [
      { ingredientName: "Tép", grams: 100 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Canh cua mồng tơi",
    regionCode: "central",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 160,
    proteinG: 14,
    carbsG: 10,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cua lam sach, giat lay nuoc cua",
      "Bước 2: Mon goi tơi nhat, rua sach, đe rao",
      "Bước 3: Đun nuoc cua voi lua nho, quay đeu",
      "Bước 4: Khi riêu cua noi len, cho mon goi tơi vao",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Tat bep, rac hanh la, tieu xay",
      "Bước 7: An nong voi com trang",
    ],
    ingredients: [
      { ingredientName: "Cua", grams: 80 },
      { ingredientName: "Mồng tơi", grams: 100 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Gia vị", grams: 3 },
    ],
  },

  // ==================== SIDE DISHES (15) ====================
  {
    nameVi: "Rau muống luộc",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 40,
    proteinG: 3,
    carbsG: 6,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Rau muống nhặt bỏ la già, ngắt khúc vừa an",
      "Bước 2: Rửa sạch, đe rao",
      "Bước 3: Đun soi nước voi muoi",
      "Bước 4: Cho rau muống vao luộc chin tai",
      "Bước 5: Vot rau ra, ngam nuoc lanh đe gion",
      "Bước 6: Bay ra dĩa, cham voi nuoc mam pha",
    ],
    ingredients: [
      { ingredientName: "Rau muống", grams: 200 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Ớt", grams: 3 },
    ],
  },
  {
    nameVi: "Canh mồng tơi cua",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 80,
    proteinG: 8,
    carbsG: 6,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Mon goi tơi nhặt lấy la non, rửa sạch",
      "Bước 2: Cua lam sach, giat lay thit va nuoc",
      "Bước 3: Đun nuoc cua voi lua nho",
      "Bước 4: Khi riêu cua noi len, cho mon goi tơi vao",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Tat bep, rac hanh la, tieu xay",
    ],
    ingredients: [
      { ingredientName: "Cua", grams: 60 },
      { ingredientName: "Mồng tơi", grams: 100 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Canh bí đỏ thịt băm",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 120,
    proteinG: 10,
    carbsG: 14,
    fatG: 3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bi đo gọt vỏ, thái miếng vừa an",
      "Bước 2: Thit heo nac bam nho",
      "Bước 3: Đun soi nước, cho bi đo vao",
      "Bước 4: Khi bi đo mem, cho thit băm vao",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Rac hanh la, tat bep",
    ],
    ingredients: [
      { ingredientName: "Bí đỏ", grams: 150 },
      { ingredientName: "Thịt heo nạc", grams: 50 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Canh rau ngót thịt băm",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 100,
    proteinG: 10,
    carbsG: 8,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Rau ngót tuot lay la, rua sach",
      "Bước 2: Thit heo nac bam nho, uop voi nuoc mam",
      "Bước 3: Đun soi nước, cho thit băm vao nan đeu",
      "Bước 4: Khi thit chin, cho rau ngot vao",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Tat bep, rac hanh la, tieu xay",
    ],
    ingredients: [
      { ingredientName: "Rau ngót", grams: 100 },
      { ingredientName: "Thịt heo nạc", grams: 50 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Canh cải ngọt tôm",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 90,
    proteinG: 10,
    carbsG: 6,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cai ngot nhat lay la, cat khuc, rua sach",
      "Bước 2: Tom boc vo, bam nho",
      "Bước 3: Đun soi nước, cho tom vao",
      "Bước 4: Khi tom chin, cho cai ngot vao",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Tat bep, rac hanh la, tieu xay",
    ],
    ingredients: [
      { ingredientName: "Cải ngọt", grams: 100 },
      { ingredientName: "Tôm", grams: 40 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Canh cải thảo",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 60,
    proteinG: 4,
    carbsG: 8,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cai thao rua sach, thai khuc vua an",
      "Bước 2: Đun soi nước voi it muoi",
      "Bước 3: Cho cai thao vao luôc",
      "Bước 4: Nem nuoc mam vua an",
      "Bước 5: Khi rau chin, vot ra to",
      "Bước 6: Chan nuoc dung, rac hanh la, tieu",
    ],
    ingredients: [
      { ingredientName: "Cải thảo", grams: 150 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Rau dền luộc",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 40,
    proteinG: 3,
    carbsG: 6,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Rau dền nhặt la non, bo la gia",
      "Bước 2: Rua sach, đe rao",
      "Bước 3: Đun soi nước voi muoi",
      "Bước 4: Cho rau dền vao luộc chin",
      "Bước 5: Vot rau ra dĩa",
      "Bước 6: Cham voi nuoc mam pha chanh ot",
    ],
    ingredients: [
      { ingredientName: "Rau dền", grams: 200 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Ớt", grams: 3 },
    ],
  },
  {
    nameVi: "Bắp cải xào tỏi",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 80,
    proteinG: 3,
    carbsG: 8,
    fatG: 5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bap cai thai soi vua an, rua sach",
      "Bước 2: Toi bam nho",
      "Bước 3: Phi thom toi voi dau an",
      "Bước 4: Cho bap cai vao xao lua lon",
      "Bước 5: Nem nuoc mam, muoi vua an",
      "Bước 6: Khi bap cai chin, tat bep, bay ra dĩa",
    ],
    ingredients: [
      { ingredientName: "Bắp cải", grams: 200 },
      { ingredientName: "Tỏi", grams: 8 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Nấm xào tỏi",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 60,
    proteinG: 4,
    carbsG: 6,
    fatG: 3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Nam rửa sạch, cat đoi hoặc thai lat",
      "Bước 2: Toi bam nho",
      "Bước 3: Phi thom toi voi dau an",
      "Bước 4: Cho nam vao xao lua lon",
      "Bước 5: Nem nuoc mam, muoi, tieu vua an",
      "Bước 6: Khi nam chin, tat bep, bay ra dĩa",
    ],
    ingredients: [
      { ingredientName: "Nấm", grams: 150 },
      { ingredientName: "Tỏi", grams: 8 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Nộm đu đủ",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 80,
    proteinG: 2,
    carbsG: 15,
    fatG: 2,
    mealTime: ["lunch", "dinner", "snack"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đu đủ xanh gọt vỏ, bào sợi",
      "Bước 2: Ngam đu đủ voi nuoc muoi 10 phut, vat rao",
      "Bước 3: Trộn nuoc mam, giam, đuong voi tieu",
      "Bước 4: Trộn đu đủ voi hon hợp nuoc cham",
      "Bước 5: Them dưa leo thai lat, rau mui",
      "Bước 6: Rac lac rang len mat",
    ],
    ingredients: [
      { ingredientName: "Đu đủ", grams: 100 },
      { ingredientName: "Dưa leo", grams: 30 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Giấm", grams: 10 },
      { ingredientName: "Đường", grams: 8 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Rau mùi", grams: 5 },
      { ingredientName: "Muối", grams: 3 },
    ],
  },
  {
    nameVi: "Cà rốt luộc",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 50,
    proteinG: 1,
    carbsG: 12,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Ca rot got vo, rửa sach",
      "Bước 2: Cat khuc vua an hoặc thai lat",
      "Bước 3: Đun soi nước voi it muoi",
      "Bước 4: Cho ca rot vao luôc chin",
      "Bước 5: Vot ra dĩa, đe ngui",
      "Bước 6: An kem voi muoi tieu hoac mayonaise",
    ],
    ingredients: [
      { ingredientName: "Cà rốt", grams: 150 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Dưa leo muối chua",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 phần",
    servingGrams: 100,
    calories: 20,
    proteinG: 1,
    carbsG: 4,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Dưa leo rửa sach, thai lat hoặc chẻ doc",
      "Bước 2: Pha nuoc muoi, giam, đuong voi ti le",
      "Bước 3: Cho dưa leo vao, ngam 10 phut",
      "Bước 4: Vot ra, đe rao",
      "Bước 5: Them ot thai lat, rau mui",
      "Bước 6: Bay ra dĩa, an kem bua com",
    ],
    ingredients: [
      { ingredientName: "Dưa leo", grams: 100 },
      { ingredientName: "Muối", grams: 5 },
      { ingredientName: "Giấm", grams: 10 },
      { ingredientName: "Đường", grams: 8 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Rau mùi", grams: 3 },
    ],
  },
  {
    nameVi: "Đậu phụ sốt cà chua",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 120,
    proteinG: 10,
    carbsG: 8,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu phụ thai mieng vua an",
      "Bước 2: Chien đau phu voi dau an cho vang",
      "Bước 3: Ca chua thai mieng, xao voi hanh tim",
      "Bước 4: Cho đau phu vao noi, đo nuoc xam xap",
      "Bước 5: Nem nuoc mam, muoi, đuong vua an",
      "Bước 6: Khi sot sanh lai, tat bep, bay ra dĩa",
    ],
    ingredients: [
      { ingredientName: "Đậu phụ", grams: 150 },
      { ingredientName: "Cà chua", grams: 80 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Đường", grams: 5 },
    ],
  },
  {
    nameVi: "Cà tím nướng",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 60,
    proteinG: 3,
    carbsG: 8,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Ca tim rửa sach, đe nguyen qua",
      "Bước 2: Nuong ca tim tren bep than hoa hay lo nuong",
      "Bước 3: Khi vo chuyen mau, vo chin đeu, boc vo",
      "Bước 4: Xe ca tim thanh soi",
      "Bước 5: Pha nuoc mam chanh ot voi toi bam",
      "Bước 6: Chan len ca tim, rac hanh phi",
    ],
    ingredients: [
      { ingredientName: "Cà tím", grams: 200 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Chanh", grams: 8 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Tỏi", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Cải bẹ xanh luộc",
    regionCode: "central",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 35,
    proteinG: 3,
    carbsG: 5,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cai be xanh rửa sach, cat khuc",
      "Bước 2: Đun soi nước voi muoi",
      "Bước 3: Cho cai be xanh vao luôc",
      "Bước 4: Khi rau chin, vot ra dĩa",
      "Bước 5: Chan nuoc mam pha chanh ot",
      "Bước 6: An kem voi com nong",
    ],
    ingredients: [
      { ingredientName: "Cải bẹ xanh", grams: 200 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Chanh", grams: 5 },
      { ingredientName: "Ớt", grams: 3 },
    ],
  },

  // ==================== SNACKS (15) ====================
  {
    nameVi: "Bánh bột lọc tôm",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 220,
    proteinG: 8,
    carbsG: 35,
    fatG: 5,
    mealTime: ["snack"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Tom boc vo, bam nho, xao voi hanh tim",
      "Bước 2: Bot loc nhao voi nuoc soi, nhan đeu",
      "Bước 3: Can bot thanh mieng tron, cho nhan tom vao",
      "Bước 4: Goi kin, nan lai thanh hinh tron dai",
      "Bước 5: Xep banh vao xửng, hap 15 phut",
      "Bước 6: Bay ra dĩa, chan nuoc mam pha va hanh phi",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 50 },
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Dầu ăn", grams: 8 },
    ],
  },
  {
    nameVi: "Bánh bèo chén",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 180,
    proteinG: 5,
    carbsG: 30,
    fatG: 4,
    mealTime: ["snack"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 25,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Bot gao pha voi nuoc lanh, khuay đeu",
      "Bước 2: Đe bot nghi 20 phut, khuay lai",
      "Bước 3: Quet dau an vao chung nho, đot bot vao",
      "Bước 4: Xep chung vao xửng hap 10 phut",
      "Bước 5: Tom bam xao voi hanh tim",
      "Bước 6: Bot ra chung, rac tom, hanh phi, nuoc mam",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Tôm", grams: 30 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 8 },
      { ingredientName: "Nước mắm", grams: 5 },
    ],
  },
  {
    nameVi: "Bánh nậm chay",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 160,
    proteinG: 3,
    carbsG: 32,
    fatG: 2,
    mealTime: ["snack"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Bot gao pha voi nuoc, khuay đeu",
      "Bước 2: Nam ngam nuoc, thai nho, xao voi hanh tim",
      "Bước 3: Đot bot len la chuoi hoặc giay nan",
      "Bước 4: Cho nhan nam len giua",
      "Bước 5: Gap la hoặc giay lai, xep vao xửng",
      "Bước 6: Hap 15 phut, lay ra đe ngui",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Nấm", grams: 30 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Bánh khoái bò",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "2 cái",
    servingGrams: 200,
    calories: 340,
    proteinG: 16,
    carbsG: 28,
    fatG: 18,
    mealTime: ["snack"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Bot gao, bot nghe pha voi nuoc lanh",
      "Bước 2: Thit bo thai lat mong, uop voi tieu, nuoc mam",
      "Bước 3: Đun chao dau nong, đot bott vao dan đeu",
      "Bước 4: Khi bot hoi chin, cho thit bo, gia do, hanh tay",
      "Bước 5: Gap đoi banh lai, chien đen khi vang gion",
      "Bước 6: Bay ra dĩa, an kem voi rau song va nuoc cham",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Thịt bò", grams: 60 },
      { ingredientName: "Giá đỗ", grams: 30 },
      { ingredientName: "Hành tây", grams: 20 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Nghệ", grams: 3 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Bánh lọc trần",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 200,
    proteinG: 6,
    carbsG: 34,
    fatG: 4,
    mealTime: ["snack"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Bot loc nhao voi nuoc soi, nhan mem",
      "Bước 2: Tom boc vo, đe nguyen hoặc băm nho",
      "Bước 3: Thit heo nac bam nho, tron voi tieu",
      "Bước 4: Can bot, cho nhan tom thit vao giua",
      "Bước 5: Goi kin, vo tron, tha vao nuoc soi",
      "Bước 6: Khi banh noi len, vot ra, đe rao",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Tôm", grams: 30 },
      { ingredientName: "Thịt heo nạc", grams: 20 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Nem lụi ram",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 320,
    proteinG: 18,
    carbsG: 20,
    fatG: 18,
    mealTime: ["snack", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thit heo nac bam nho, tron voi tom bam",
      "Bước 2: Hanh tim bam, tieu, nuoc mam, duong tron đeu",
      "Bước 3: Nan thit vao que tre, nam ep đeu",
      "Bước 4: Nuong tren bep than hoa đen chin vang",
      "Bước 5: Chien lai voi dau an cho gion",
      "Bước 6: Bay ra dĩa, an kem voi bun va rau song",
    ],
    ingredients: [
      { ingredientName: "Thịt heo nạc", grams: 100 },
      { ingredientName: "Tôm", grams: 40 },
      { ingredientName: "Hành tím", grams: 15 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Bún", grams: 100 },
    ],
  },
  {
    nameVi: "Chè nhãn hạt sen",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 200,
    calories: 160,
    proteinG: 4,
    carbsG: 34,
    fatG: 1,
    mealTime: ["snack"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Hat sen tuoi boc vo, bo tam",
      "Bước 2: Nau hat sen voi nuoc đen chin mem",
      "Bước 3: Đuong cho vao khuay tan",
      "Bước 4: Nhao bot mi voi nuoc, chien banh nhan",
      "Bước 5: Cho banh nhan vao noi che, nau them 5 phut",
      "Bước 6: Tat bep, đe ngui, an mat hoac nong",
    ],
    ingredients: [
      { ingredientName: "Bột mì", grams: 50 },
      { ingredientName: "Đậu xanh", grams: 30 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Dầu ăn", grams: 5 },
    ],
  },
  {
    nameVi: "Chè bí đỏ",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 200,
    calories: 180,
    proteinG: 2,
    carbsG: 40,
    fatG: 2,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bi đo got vo, thai mieng vua an",
      "Bước 2: Đun soi nước, cho bi đo vao",
      "Bước 3: Nau đen khi bi đo mem",
      "Bước 4: Cho duong vao, khuay đeu tan",
      "Bước 5: Them nuoc cot dưa vao, khuay nhe",
      "Bước 6: Tat bep, đe ngui, an mat",
    ],
    ingredients: [
      { ingredientName: "Bí đỏ", grams: 150 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Dừa", grams: 30 },
    ],
  },
  {
    nameVi: "Chè đậu đen",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 200,
    calories: 200,
    proteinG: 8,
    carbsG: 38,
    fatG: 3,
    mealTime: ["snack"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu đen ngâm nước 2 tieng, vo sach",
      "Bước 2: Nau đau đen voi nuoc đen chin mem",
      "Bước 3: Cho duong vao, khuay đeu tan",
      "Bước 4: Them nuoc cot dưa vao",
      "Bước 5: Khuay đeu, nau them 5 phut",
      "Bước 6: Tat bep, đe ngui, an mat hoac nong",
    ],
    ingredients: [
      { ingredientName: "Đậu đen", grams: 80 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Dừa", grams: 30 },
    ],
  },
  {
    nameVi: "Chè khoai tây",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 200,
    calories: 160,
    proteinG: 2,
    carbsG: 36,
    fatG: 1,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Khoai tây got vo, rửa sach, thai hat lua",
      "Bước 2: Nau khoai tây voi nuoc đen chin mem",
      "Bước 3: Nghien nho khoai tây",
      "Bước 4: Cho duong vao, khuay đeu",
      "Bước 5: Them nuoc cot dưa vao",
      "Bước 6: Tat bep, đe ngui, an mat",
    ],
    ingredients: [
      { ingredientName: "Khoai tây", grams: 150 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Dừa", grams: 20 },
    ],
  },
  {
    nameVi: "Bánh thanh ước",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "3 cái",
    servingGrams: 100,
    calories: 250,
    proteinG: 4,
    carbsG: 35,
    fatG: 10,
    mealTime: ["snack"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Bot gao, duong, nuoc cot dưa tron đeu",
      "Bước 2: Nhan bot mem, nam thanh vien tron",
      "Bước 3: Vung rang vang, giat nho",
      "Bước 4: Lan vien bot qua vung",
      "Bước 5: Chien ngap dau đen khi vang đeu",
      "Bước 6: Vot ra giay tham dau, đe ngui",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 60 },
      { ingredientName: "Đường", grams: 20 },
      { ingredientName: "Dừa", grams: 20 },
      { ingredientName: "Vừng", grams: 15 },
      { ingredientName: "Dầu ăn", grams: 15 },
    ],
  },
  {
    nameVi: "Bánh khoai lang",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "3 cái",
    servingGrams: 150,
    calories: 280,
    proteinG: 3,
    carbsG: 42,
    fatG: 12,
    mealTime: ["snack"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Khoai lang got vo, rửa sach, bào sợi",
      "Bước 2: Tron khoai lang voi bot gao, duong, vung",
      "Bước 3: Nan khoai thanh mieng tron dep",
      "Bước 4: Chien ngap dau đen khi vang gion",
      "Bước 5: Vot ra giay tham dau",
      "Bước 6: Bay ra dĩa, an nong hoặc ngui",
    ],
    ingredients: [
      { ingredientName: "Khoai lang", grams: 100 },
      { ingredientName: "Bột gạo", grams: 30 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Vừng", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 15 },
    ],
  },
  {
    nameVi: "Bánh gạo nướng",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "3 cái",
    servingGrams: 100,
    calories: 220,
    proteinG: 3,
    carbsG: 38,
    fatG: 6,
    mealTime: ["snack"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bap rang no vo, đe ngui",
      "Bước 2: Tron bap rang voi duong, vung",
      "Bước 3: Hoa tan duong voi it nuoc nong",
      "Bước 4: Tron bap rang voi nuoc duong",
      "Bước 5: Nan thanh mieng tron, đe ngui",
      "Bước 6: Khi banh cung, cat mieng vua an",
    ],
    ingredients: [
      { ingredientName: "Ngô", grams: 80 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Vừng", grams: 10 },
      { ingredientName: "Lạc", grams: 15 },
    ],
  },
  {
    nameVi: "Chả ram tôm đất",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 280,
    proteinG: 14,
    carbsG: 20,
    fatG: 16,
    mealTime: ["snack"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 15,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Tom đat boc vo, bam nho",
      "Bước 2: Thit heo nac bam nhuyen, tron voi tom",
      "Bước 3: Hanh tim, tieu, nuoc mam, duong tron đeu",
      "Bước 4: Banh trang nhuom nuoc mem",
      "Bước 5: Cuô nhan vao banh trang, nan thanh hinh tru",
      "Bước 6: Chien ngap dau đen khi vang gion",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 60 },
      { ingredientName: "Thịt heo nạc", grams: 40 },
      { ingredientName: "Bánh tráng", grams: 30 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Nước mắm", grams: 8 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Tiêu", grams: 2 },
      { ingredientName: "Dầu ăn", grams: 15 },
    ],
  },
  {
    nameVi: "Chuối chiên",
    regionCode: "central",
    categorySlug: "snacks",
    servingSize: "3 cái",
    servingGrams: 150,
    calories: 280,
    proteinG: 3,
    carbsG: 42,
    fatG: 12,
    mealTime: ["snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Chuối chín boc vo, bo đoi theo chieu doc",
      "Bước 2: Bot gao pha voi nuoc lanh, chut muoi",
      "Bước 3: Nhung mieng chuối vao bot",
      "Bước 4: Chien ngap dau đen khi vang gion",
      "Bước 5: Vot ra giay tham dau",
      "Bước 6: Bay ra dĩa, rắc vung rang va duong",
    ],
    ingredients: [
      { ingredientName: "Chuối", grams: 100 },
      { ingredientName: "Bột gạo", grams: 30 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Vừng", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Muối", grams: 1 },
    ],
  },

  // ==================== DRINKS (5) ====================
  {
    nameVi: "Nước chanh",
    regionCode: "central",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 60,
    proteinG: 0,
    carbsG: 14,
    fatG: 0,
    mealTime: ["breakfast", "lunch", "dinner", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Chanh cat đoi, vat lay nuoc cot",
      "Bước 2: Pha nuoc chan voi duong va muoi",
      "Bước 3: Khuay đeu cho tan duong",
      "Bước 4: Them đa vao ly",
      "Bước 5: Do nuoc chanh vao ly",
      "Bước 6: Trang tri voi la bac ha hoặc lat chanh",
    ],
    ingredients: [
      { ingredientName: "Chanh", grams: 30 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Trà lài",
    regionCode: "central",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 10,
    proteinG: 0,
    carbsG: 2,
    fatG: 0,
    mealTime: ["breakfast", "lunch", "dinner", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đun soi nước",
      "Bước 2: Cho tra lai vao an am, đe ngam 5 phut",
      "Bước 3: Loc bot lai, lay nuoc tra",
      "Bước 4: Neu thich, cho duong vao khuay tan",
      "Bước 5: Do tra ra ly",
      "Bước 6: Thuong thuc nong hoac cho đa",
    ],
    ingredients: [
      { ingredientName: "Trà", grams: 5 },
      { ingredientName: "Đường", grams: 10 },
    ],
  },
  {
    nameVi: "Sinh tố mãng cầu",
    regionCode: "central",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 200,
    proteinG: 3,
    carbsG: 30,
    fatG: 8,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Mang cau chin boc vo, bo hat, lay thit",
      "Bước 2: Cho thit mang cau, sua tuoi vao may xay",
      "Bước 3: Them sua đặc, duong vao",
      "Bước 4: Xay nhan đen min",
      "Bước 5: Rot ra ly",
      "Bước 6: Them đa vay vao, trang tri",
    ],
    ingredients: [
      { ingredientName: "Sữa tươi", grams: 100 },
      { ingredientName: "Sữa đặc", grams: 20 },
      { ingredientName: "Đường", grams: 10 },
    ],
  },
  {
    nameVi: "Cà phê sữa",
    regionCode: "central",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 200,
    calories: 120,
    proteinG: 3,
    carbsG: 18,
    fatG: 4,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cho ca phe vao phin, dan đeu",
      "Bước 2: Chân 1 lớp nuoc soi, đe 1 phut",
      "Bước 3: Cho sữa đặc vao đay ly",
      "Bước 4: Đo nuoc soi vao phin, đay nap",
      "Bước 5: Đoi ca phe nho giot xuong ly",
      "Bước 6: Khuay đeu, them đa neu thich",
    ],
    ingredients: [
      { ingredientName: "Cà phê", grams: 15 },
      { ingredientName: "Sữa đặc", grams: 25 },
    ],
  },
  {
    nameVi: "Sữa chua uống",
    regionCode: "central",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 180,
    proteinG: 5,
    carbsG: 30,
    fatG: 5,
    mealTime: ["breakfast", "snack"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cho sua chua, sua tuoi, sua đặc vao may xay",
      "Bước 2: Them đuong vao",
      "Bước 3: Xay nhan đen min",
      "Bước 4: Đo đa vao may xay, xay them",
      "Bước 5: Rot ra ly",
      "Bước 6: Trang tri them trai cây",
    ],
    ingredients: [
      { ingredientName: "Sữa chua", grams: 100 },
      { ingredientName: "Sữa tươi", grams: 100 },
      { ingredientName: "Sữa đặc", grams: 20 },
      { ingredientName: "Đường", grams: 10 },
    ],
  },
]

export async function seedFoodsMoreCentral(prisma: PrismaClient) {
  const regions = await prisma.region.findMany()
  const categories = await prisma.category.findMany()
  const regionMap = Object.fromEntries(regions.map(r => [r.code, r.id]))
  const categoryMap = Object.fromEntries(categories.map(c => [c.slug, c.id]))

  for (const f of foods) {
    const foodData = {
      id: f.nameVi,
      nameVi: f.nameVi,
      servingSize: f.servingSize,
      servingGrams: f.servingGrams,
      calories: f.calories,
      proteinG: f.proteinG,
      carbsG: f.carbsG,
      fatG: f.fatG,
      mealTime: f.mealTime,
      recipeSteps: f.recipeSteps ?? [],
      prepTimeMinutes: f.prepTimeMinutes ?? null,
      cookTimeMinutes: f.cookTimeMinutes ?? null,
      difficulty: f.difficulty ?? null,
      isVerified: true,
      regionId: regionMap[f.regionCode],
      categoryId: categoryMap[f.categorySlug],
    }

    await prisma.food.upsert({
      where: { id: f.nameVi },
      update: foodData,
      create: {
        ...foodData,
        ingredients: {
          create: (f.ingredients ?? []).map(ing => ({
            ingredientName: ing.ingredientName,
            grams: ing.grams,
            proteinG: 0,
            carbsG: 0,
            fatG: 0,
          })),
        },
      },
    })
  }
  console.log(`✅ Seeded ${foods.length} central dishes (more)`)
}
