import { PrismaClient } from "../../src/generated/prisma"
import { type FoodSeed } from "./types"

const foods: FoodSeed[] = [
  // ======= MAIN DISHES (30) =======
  {
    nameVi: "Hủ tiếu Nam Vang",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 20,
    carbsG: 48,
    fatG: 12,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 45,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ngâm xương heo và tôm khô, ninh xương lấy nước dùng trong khoảng 1 tiếng",
      "Bước 2: Sơ chế tôm tươi, lột vỏ và rút chỉ lưng",
      "Bước 3: Thái thịt heo thành lát mỏng vừa ăn",
      "Bước 4: Luộc bánh phở qua nước sôi, trụng nhanh rồi vớt ra tô",
      "Bước 5: Xếp thịt, tôm, giá đỗ, rau thơm lên trên bánh phở",
      "Bước 6: Chan nước dùng nóng hổi vào tô, rắc hành phi và tiêu lên mặt",
    ],
    ingredients: [
      { ingredientName: "Bánh phở", grams: 200 },
      { ingredientName: "Thịt heo nạc", grams: 80 },
      { ingredientName: "Tôm", grams: 50 },
      { ingredientName: "Giá đỗ", grams: 30 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Đường", grams: 5 },
    ],
  },
  {
    nameVi: "Cơm tấm sườn bì chả",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 450,
    calories: 620,
    proteinG: 32,
    carbsG: 70,
    fatG: 22,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 50,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Ướp sườn non với tỏi băm, nước mắm, đường, tiêu trong 30 phút",
      "Bước 2: Nướng sườn trên than hoa hoặc lò nướng đến khi chín vàng",
      "Bước 3: Làm bì heo: thái thịt heo luộc sợi mỏng, trộn với thính gạo",
      "Bước 4: Hấp trứng và thịt làm chả trứng hấp kiểu miền Nam",
      "Bước 5: Nấu cơm tấm bằng gạo tấm, xới ra dĩa",
      "Bước 6: Xếp sườn, bì, chả lên cơm, ăn kèm dưa leo và cà chua",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Thịt heo nạc", grams: 100 },
      { ingredientName: "Thịt heo ba chỉ", grams: 50 },
      { ingredientName: "Trứng gà", grams: 50 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Dưa leo", grams: 30 },
      { ingredientName: "Cà chua", grams: 30 },
    ],
  },
  {
    nameVi: "Bánh xèo miền Nam",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "2 cái",
    servingGrams: 300,
    calories: 420,
    proteinG: 18,
    carbsG: 38,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Pha bột bánh xèo với nước cốt dừa, bột nghệ, hành lá cắt nhỏ",
      "Bước 2: Làm nhân: xào tôm và thịt heo ba chỉ với gia vị",
      "Bước 3: Đổ bột vào chảo nóng có dầu, tráng mỏng đều",
      "Bước 4: Cho nhân lên mặt bánh khi bột còn ướt, đậy nắp chừng 2 phút",
      "Bước 5: Gấp đôi bánh lại, chiên thêm đến khi giòn",
      "Bước 6: Dọn kèm rau sống và nước mắm chua ngọt",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 100 },
      { ingredientName: "Tôm", grams: 60 },
      { ingredientName: "Thịt heo ba chỉ", grams: 50 },
      { ingredientName: "Dầu ăn", grams: 20 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Bột nghệ", grams: 3 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Dừa", grams: 50 },
    ],
  },
  {
    nameVi: "Lẩu mắm",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 nồi (4 người)",
    servingGrams: 1200,
    calories: 320,
    proteinG: 28,
    carbsG: 18,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Phi thơm tỏi và sả, cho mắm vào xào cho thơm",
      "Bước 2: Đổ nước dừa tươi vào nồi, đun sôi, nêm nếm gia vị",
      "Bước 3: Cho cá lóc và tôm vào nồi nước lẩu đang sôi",
      "Bước 4: Chuẩn bị rau nhúng: rau muống, bông súng, cải bẹ xanh",
      "Bước 5: Bày biện nồi lẩu lên bếp từ giữa bàn",
      "Bước 6: Dùng kèm bún tươi và rau sống các loại",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 200 },
      { ingredientName: "Tôm", grams: 100 },
      { ingredientName: "Rau muống", grams: 100 },
      { ingredientName: "Cải bẹ xanh", grams: 80 },
      { ingredientName: "Sả", grams: 30 },
      { ingredientName: "Tỏi", grams: 15 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Dừa", grams: 200 },
      { ingredientName: "Ớt", grams: 10 },
    ],
  },
  {
    nameVi: "Cá kho tộ",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 310,
    proteinG: 28,
    carbsG: 12,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 60,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cá basa cắt khúc vừa ăn, ướp với nước mắm, đường, tiêu, tỏi băm",
      "Bước 2: Đun nước màu từ đường thắng, đổ vào tộ đất",
      "Bước 3: Xếp cá vào tộ, cho nước dừa tươi ngập mặt cá",
      "Bước 4: Kho lửa nhỏ đến khi nước rút cạn keo lại",
      "Bước 5: Rắc tiêu và ớt lên trên khi gần tắt bếp",
      "Bước 6: Dùng với cơm trắng nóng và rau luộc",
    ],
    ingredients: [
      { ingredientName: "Cá basa", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Tiêu", grams: 3 },
      { ingredientName: "Ớt", grams: 5 },
    ],
  },
  {
    nameVi: "Canh chua cá lóc",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 210,
    proteinG: 22,
    carbsG: 14,
    fatG: 8,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cá lóc làm sạch, cắt khúc vừa ăn",
      "Bước 2: Nấu nước sôi, cho me vào hòa tan lấy nước chua",
      "Bước 3: Cho cá vào nồi nước me đang sôi",
      "Bước 4: Thêm cà chua, giá đỗ, rau muống cắt khúc",
      "Bước 5: Nêm nếm nước mắm, đường, muối cho vừa ăn",
      "Bước 6: Rắc hành lá, ngò om và ớt lên trên, tắt bếp",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 200 },
      { ingredientName: "Cà chua", grams: 80 },
      { ingredientName: "Giá đỗ", grams: 50 },
      { ingredientName: "Rau muống", grams: 60 },
      { ingredientName: "Me", grams: 30 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Ớt", grams: 5 },
    ],
  },
  {
    nameVi: "Bún mắm",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 410,
    proteinG: 26,
    carbsG: 52,
    fatG: 14,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 50,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Phi thơm tỏi, sả với mắm nêm, mắm tôm",
      "Bước 2: Ninh xương heo lấy nước dùng, cho mắm đã phi vào",
      "Bước 3: Cho cá basa, tôm, mực vào nồi nước dùng",
      "Bước 4: Trụng bún qua nước sôi, cho ra tô",
      "Bước 5: Xếp thịt heo quay, cá, tôm, mực lên bún",
      "Bước 6: Chan nước dùng nóng, thêm rau sống và ớt",
    ],
    ingredients: [
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Cá basa", grams: 80 },
      { ingredientName: "Tôm", grams: 50 },
      { ingredientName: "Mực", grams: 40 },
      { ingredientName: "Thịt heo ba chỉ", grams: 60 },
      { ingredientName: "Mắm nêm", grams: 20 },
      { ingredientName: "Sả", grams: 20 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Rau muống", grams: 50 },
    ],
  },
  {
    nameVi: "Cơm chiên Dương Châu",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 350,
    calories: 480,
    proteinG: 20,
    carbsG: 55,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đập trứng gà đánh tan, chiên sơ trong chảo dầu nóng",
      "Bước 2: Xào tôm và chả lụa cắt hạt lựu chín tới",
      "Bước 3: Cho cơm nguội vào chảo, đảo đều tay",
      "Bước 4: Nêm nước mắm, bột ngọt, tiêu, đảo cho cơm săn",
      "Bước 5: Thêm hành lá và dưa leo cắt nhỏ trước khi tắt bếp",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Trứng gà", grams: 50 },
      { ingredientName: "Tôm", grams: 40 },
      { ingredientName: "Chả lụa", grams: 40 },
      { ingredientName: "Dầu ăn", grams: 20 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Dưa leo", grams: 30 },
    ],
  },
  {
    nameVi: "Gỏi cuốn tôm thịt",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "5 cuốn",
    servingGrams: 250,
    calories: 240,
    proteinG: 18,
    carbsG: 28,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Luộc tôm chín, lột vỏ, chẻ đôi",
      "Bước 2: Luộc thịt heo, thái lát mỏng mềm",
      "Bước 3: Nhúng bánh tráng qua nước cho mềm dẻo",
      "Bước 4: Xếp rau xà lách, bún, tôm, thịt, giá đỗ lên bánh tráng",
      "Bước 5: Cuốn chặt tay, bày ra dĩa",
      "Bước 6: Pha nước chấm từ nước mắm, chanh, tỏi, ớt, đường",
    ],
    ingredients: [
      { ingredientName: "Bánh tráng", grams: 50 },
      { ingredientName: "Tôm", grams: 60 },
      { ingredientName: "Thịt heo nạc", grams: 60 },
      { ingredientName: "Bún", grams: 80 },
      { ingredientName: "Giá đỗ", grams: 30 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Chanh", grams: 15 },
      { ingredientName: "Tỏi", grams: 5 },
    ],
  },
  {
    nameVi: "Bánh khọt",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "10 cái",
    servingGrams: 250,
    calories: 340,
    proteinG: 14,
    carbsG: 30,
    fatG: 18,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Pha bột bánh khọt với nước cốt dừa, bột nghệ, muối",
      "Bước 2: Tôm lột vỏ, ướp với gia vị và hành tím",
      "Bước 3: Đổ bột vào khuôn bánh khọt đã nóng dầu",
      "Bước 4: Cho tôm lên mặt bánh, đậy nắp chờ chín",
      "Bước 5: Lấy bánh ra dĩa, ăn kèm rau sống và nước mắm chua ngọt",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 100 },
      { ingredientName: "Tôm", grams: 80 },
      { ingredientName: "Dừa", grams: 60 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Bột nghệ", grams: 2 },
    ],
  },
  {
    nameVi: "Cá lóc chiên xù",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 280,
    calories: 390,
    proteinG: 30,
    carbsG: 20,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cá lóc làm sạch, khứa vài đường trên thân cá",
      "Bước 2: Ướp cá với muối, tiêu, tỏi băm, nước mắm 15 phút",
      "Bước 3: Lăn cá qua bột mì và bột chiên xù",
      "Bước 4: Chiên cá trong chảo dầu nóng đến khi vàng giòn",
      "Bước 5: Vớt cá ra dĩa có giấy thấm dầu",
      "Bước 6: Dùng với nước mắm chua ngọt và rau sống",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 200 },
      { ingredientName: "Bột mì", grams: 30 },
      { ingredientName: "Dầu ăn", grams: 20 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Tiêu", grams: 2 },
    ],
  },
  {
    nameVi: "Thịt kho tàu",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 300,
    calories: 420,
    proteinG: 24,
    carbsG: 18,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 70,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thịt heo ba chỉ cắt miếng vuông, luộc sơ cho săn",
      "Bước 2: Thắng đường làm nước màu caramel",
      "Bước 3: Cho thịt vào xào săn với nước màu, tỏi, hành tím",
      "Bước 4: Đổ nước dừa tươi vào ngập thịt, nêm nước mắm",
      "Bước 5: Luộc trứng cút, bóc vỏ, cho vào nồi thịt",
      "Bước 6: Kho lửa nhỏ đến khi thịt mềm, nước keo sánh",
    ],
    ingredients: [
      { ingredientName: "Thịt heo ba chỉ", grams: 200 },
      { ingredientName: "Trứng gà", grams: 100 },
      { ingredientName: "Dừa", grams: 100 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Tỏi", grams: 10 },
    ],
  },
  {
    nameVi: "Cá thu kho riềng",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 340,
    proteinG: 30,
    carbsG: 8,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cá thu cắt khúc, rửa sạch, để ráo",
      "Bước 2: Giã riềng, tỏi, ớt với một ít nước mắm",
      "Bước 3: Ướp cá với hỗn hợp riềng, gia vị trong 20 phút",
      "Bước 4: Xếp cá vào nồi, cho nước dừa và nước màu vào",
      "Bước 5: Kho lửa nhỏ đến khi nước rút sền sệt",
      "Bước 6: Rắc tiêu và hành lá lên trên",
    ],
    ingredients: [
      { ingredientName: "Cá thu", grams: 200 },
      { ingredientName: "Gừng", grams: 15 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Lẩu cá kèo",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 nồi (4 người)",
    servingGrams: 1200,
    calories: 280,
    proteinG: 24,
    carbsG: 16,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cá kèo làm sạch nhớt, để nguyên con",
      "Bước 2: Phi thơm tỏi, sả, hành tím với dầu",
      "Bước 3: Cho cá vào xào sơ, đổ nước dừa tươi",
      "Bước 4: Thêm cà chua, me tạo vị chua, nêm gia vị",
      "Bước 5: Bày nồi lẩu với các loại rau nhúng",
      "Bước 6: Dùng kèm bún hoặc mì tươi",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 200 },
      { ingredientName: "Sả", grams: 30 },
      { ingredientName: "Cà chua", grams: 80 },
      { ingredientName: "Me", grams: 30 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Rau muống", grams: 100 },
      { ingredientName: "Giá đỗ", grams: 60 },
      { ingredientName: "Ớt", grams: 5 },
    ],
  },
  {
    nameVi: "Bánh canh giò heo",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 420,
    calories: 400,
    proteinG: 22,
    carbsG: 50,
    fatG: 14,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 60,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Giò heo chặt miếng vừa ăn, rửa sạch",
      "Bước 2: Ninh giò heo với nước dừa và hành tím đến khi mềm",
      "Bước 3: Nấu nước dùng với tôm khô, nêm nước mắm",
      "Bước 4: Bắc nồi nước sôi khác luộc bánh canh",
      "Bước 5: Cho bánh canh ra tô, xếp giò heo và trứng cút",
      "Bước 6: Chan nước dùng nóng, rắc tiêu và hành lá",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 150 },
      { ingredientName: "Thịt heo nạc", grams: 100 },
      { ingredientName: "Tôm", grams: 30 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Dừa", grams: 100 },
    ],
  },
  {
    nameVi: "Ốc len xào dừa",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 250,
    proteinG: 18,
    carbsG: 10,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Ốc len ngâm nước lạnh với ớt để nhả hết nhớt",
      "Bước 2: Luộc ốc sơ qua nước sôi, vớt ra",
      "Bước 3: Phi thơm tỏi, sả với dầu dừa",
      "Bước 4: Cho ốc vào xào với nước cốt dừa, nước mắm",
      "Bước 5: Thêm bột sắn dây pha nước tạo sánh",
      "Bước 6: Rắc tiêu, ớt, hành lá, ăn với bánh mì",
    ],
    ingredients: [
      { ingredientName: "Ốc", grams: 150 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Sả", grams: 15 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Bánh mì", grams: 60 },
    ],
  },
  {
    nameVi: "Cơm gà tam giác mạch",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 400,
    calories: 520,
    proteinG: 30,
    carbsG: 58,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thịt gà đùi luộc chín, xé nhỏ hoặc thái miếng",
      "Bước 2: Vo gạo nấu cơm với nước luộc gà cho thơm",
      "Bước 3: Pha nước mắm gừng chấm gà",
      "Bước 4: Thái dưa leo, cà chua, rau thơm",
      "Bước 5: Xếp cơm, gà và rau lên dĩa, rắc tiêu",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 200 },
      { ingredientName: "Thịt gà đùi", grams: 150 },
      { ingredientName: "Dưa leo", grams: 50 },
      { ingredientName: "Cà chua", grams: 50 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Gừng", grams: 10 },
    ],
  },
  {
    nameVi: "Bún thịt nướng",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 400,
    calories: 480,
    proteinG: 26,
    carbsG: 54,
    fatG: 18,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thái thịt heo mỏng, ướp với sả, tỏi, nước mắm, mật ong",
      "Bước 2: Xiên thịt vào que tre, nướng trên than hoa",
      "Bước 3: Trụng bún qua nước sôi, bày ra dĩa",
      "Bước 4: Xếp thịt nướng, dưa leo, giá đỗ, rau thơm lên bún",
      "Bước 5: Rưới nước chấm chua ngọt lên trên",
      "Bước 6: Rắc lạc rang và hành phi",
    ],
    ingredients: [
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Thịt heo nạc", grams: 120 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Mật ong", grams: 10 },
      { ingredientName: "Sả", grams: 15 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Lạc", grams: 15 },
    ],
  },
  {
    nameVi: "Lẩu thái hải sản",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 nồi (4 người)",
    servingGrams: 1300,
    calories: 340,
    proteinG: 30,
    carbsG: 20,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Sơ chế tôm, mực, cá hồi: rửa sạch, cắt vừa ăn",
      "Bước 2: Phi thơm sả, tỏi với dầu, cho gia vị lẩu Thái vào",
      "Bước 3: Đổ nước dừa vào nồi, nấu sôi, thêm nước cốt chanh",
      "Bước 4: Cho hải sản vào lẩu, thêm nấm và cà chua",
      "Bước 5: Bày nồi lẩu với rau muống, bắp cải, bún",
      "Bước 6: Nêm nước mắm, ớt, me chua cho vừa ăn",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 100 },
      { ingredientName: "Mực", grams: 100 },
      { ingredientName: "Cá hồi", grams: 100 },
      { ingredientName: "Sả", grams: 30 },
      { ingredientName: "Cà chua", grams: 80 },
      { ingredientName: "Nấm", grams: 80 },
      { ingredientName: "Bún", grams: 200 },
      { ingredientName: "Rau muống", grams: 100 },
    ],
  },
  {
    nameVi: "Sườn nướng mật ong",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 300,
    calories: 480,
    proteinG: 28,
    carbsG: 24,
    fatG: 30,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Sườn non chặt miếng vừa ăn, rửa sạch",
      "Bước 2: Ướp sườn với mật ong, nước mắm, tỏi, tiêu 30 phút",
      "Bước 3: Nướng sườn trên bếp than hoặc lò nướng",
      "Bước 4: Phết thêm mật ong khi nướng để sườn bóng đẹp",
      "Bước 5: Dùng với cơm nóng và dưa leo, cà chua",
    ],
    ingredients: [
      { ingredientName: "Thịt heo nạc", grams: 200 },
      { ingredientName: "Mật ong", grams: 30 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Dưa leo", grams: 50 },
      { ingredientName: "Cà chua", grams: 50 },
    ],
  },
  {
    nameVi: "Bò kho",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 450,
    proteinG: 32,
    carbsG: 30,
    fatG: 22,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 90,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thịt bò cắt miếng vuông, ướp với tỏi, sả, nước mắm",
      "Bước 2: Xào thịt bò săn với dầu, cho bột nghệ và bột mì",
      "Bước 3: Đổ nước dừa vào ninh thịt bò lửa nhỏ",
      "Bước 4: Thêm cà rốt, khoai tây cắt miếng khi thịt gần mềm",
      "Bước 5: Nêm nước mắm, đường, tiêu cho vừa ăn",
      "Bước 6: Dùng với bánh mì hoặc bún tươi",
    ],
    ingredients: [
      { ingredientName: "Thịt bò", grams: 200 },
      { ingredientName: "Cà rốt", grams: 80 },
      { ingredientName: "Khoai tây", grams: 80 },
      { ingredientName: "Bánh mì", grams: 100 },
      { ingredientName: "Dừa", grams: 100 },
      { ingredientName: "Sả", grams: 20 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Bột nghệ", grams: 3 },
    ],
  },
  {
    nameVi: "Tôm rim mặn ngọt",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 260,
    proteinG: 26,
    carbsG: 14,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Tôm rửa sạch, cắt bỏ râu và chân",
      "Bước 2: Pha nước mắm, đường, tương ớt thành hỗn hợp rim",
      "Bước 3: Phi tỏi băm thơm với dầu",
      "Bước 4: Cho tôm vào xào nhanh lửa lớn",
      "Bước 5: Đổ hỗn hợp nước rim vào, đảo đến khi tôm thấm",
      "Bước 6: Rắc tiêu và hành lá, dùng với cơm nóng",
    ],
    ingredients: [
      { ingredientName: "Tôm", grams: 150 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Hành lá", grams: 5 },
    ],
  },
  {
    nameVi: "Thịt heo quay giòn bì",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 250,
    calories: 420,
    proteinG: 24,
    carbsG: 6,
    fatG: 34,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 40,
    cookTimeMinutes: 60,
    difficulty: "hard",
    recipeSteps: [
      "Bước 1: Thịt heo ba chỉ để nguyên miếng, luộc sơ",
      "Bước 2: Xăm đều bề mặt da, ướp thịt với ngũ vị hương và muối",
      "Bước 3: Phơi thịt ngoài gió hoặc dùng quạt cho da khô",
      "Bước 4: Chiên thịt trong chảo dầu ngập đến khi da nổ giòn",
      "Bước 5: Vớt ra để ráo dầu, thái miếng vừa ăn",
      "Bước 6: Dùng với cơm và nước mắm chua ngọt",
    ],
    ingredients: [
      { ingredientName: "Thịt heo ba chỉ", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 30 },
      { ingredientName: "Muối", grams: 5 },
      { ingredientName: "Gia vị", grams: 5 },
      { ingredientName: "Nước mắm", grams: 15 },
    ],
  },
  {
    nameVi: "Cá diêu hồng chiên nước mắm",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 con",
    servingGrams: 350,
    calories: 380,
    proteinG: 34,
    carbsG: 6,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cá diêu hồng làm sạch, khứa chéo thân cá",
      "Bước 2: Pha nước mắm, đường, tỏi, ớt băm",
      "Bước 3: Chiên cá trong dầu nóng đến khi vàng giòn hai mặt",
      "Bước 4: Đổ nước mắm pha vào chảo cá rim lửa nhỏ",
      "Bước 5: Rắc hành lá và tiêu lên cá trước khi bắc",
    ],
    ingredients: [
      { ingredientName: "Cá diêu hồng", grams: 300 },
      { ingredientName: "Dầu ăn", grams: 20 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Ớt", grams: 5 },
    ],
  },
  {
    nameVi: "Vịt nấu chao",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 350,
    calories: 420,
    proteinG: 28,
    carbsG: 12,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Thịt vịt làm sạch, chặt miếng vừa ăn",
      "Bước 2: Ướp vịt với chao, tỏi băm, đường, nước mắm 20 phút",
      "Bước 3: Phi thơm hành tỏi, xào vịt săn lại",
      "Bước 4: Đổ nước dừa vào ninh vịt đến khi mềm",
      "Bước 5: Thêm khoai môn cắt miếng vào nấu cùng",
      "Bước 6: Nêm nếm lại cho vừa ăn, rắc tiêu và hành ngò",
    ],
    ingredients: [
      { ingredientName: "Thịt vịt", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Khoai tây", grams: 100 },
      { ingredientName: "Dừa", grams: 100 },
      { ingredientName: "Gia vị", grams: 5 },
    ],
  },
  {
    nameVi: "Mì quảng",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 420,
    proteinG: 24,
    carbsG: 48,
    fatG: 16,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 45,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Tôm và thịt heo nạc xào săn với hành tỏi",
      "Bước 2: Ninh xương gà lấy nước dùng ngọt",
      "Bước 3: Cho bột nghệ vào nước dùng tạo màu vàng",
      "Bước 4: Luộc mì quảng, để ráo",
      "Bước 5: Xếp mì ra tô, thêm tôm, thịt, trứng cút",
      "Bước 6: Chan nước dùng, rắc đậu phộng và bánh tráng mè",
    ],
    ingredients: [
      { ingredientName: "Mì", grams: 200 },
      { ingredientName: "Tôm", grams: 60 },
      { ingredientName: "Thịt heo nạc", grams: 60 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Bột nghệ", grams: 3 },
      { ingredientName: "Lạc", grams: 20 },
      { ingredientName: "Bánh tráng", grams: 20 },
      { ingredientName: "Hành lá", grams: 10 },
    ],
  },
  {
    nameVi: "Cua rang me",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 con",
    servingGrams: 300,
    calories: 260,
    proteinG: 22,
    carbsG: 12,
    fatG: 14,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cua làm sạch, bỏ yếm, chặt đôi",
      "Bước 2: Chiên cua sơ qua dầu nóng cho đỏ",
      "Bước 3: Pha nước cốt me, nước mắm, đường, tỏi, ớt",
      "Bước 4: Đổ hỗn hợp me vào chảo cua đảo đều lửa lớn",
      "Bước 5: Rắc hành phi và đậu phộng lên trên",
      "Bước 6: Dùng nóng với cơm trắng",
    ],
    ingredients: [
      { ingredientName: "Cua", grams: 200 },
      { ingredientName: "Me", grams: 30 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Dầu ăn", grams: 15 },
    ],
  },
  {
    nameVi: "Bánh bèo",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "10 cái",
    servingGrams: 200,
    calories: 280,
    proteinG: 10,
    carbsG: 34,
    fatG: 12,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Pha bột gạo với nước và muối thành hỗn hợp mịn",
      "Bước 2: Đổ bột vào khuôn nhỏ, hấp chín",
      "Bước 3: Tôm băm nhỏ, xào với hành phi thơm",
      "Bước 4: Cho nhân tôm lên mặt bánh sau khi hấp",
      "Bước 5: Rắc hành phi, mỡ hành lên trên",
      "Bước 6: Dùng với nước mắm chua ngọt và ớt",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 100 },
      { ingredientName: "Tôm", grams: 60 },
      { ingredientName: "Hành tím", grams: 15 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Cá trê chiên bột",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 dĩa",
    servingGrams: 300,
    calories: 380,
    proteinG: 26,
    carbsG: 22,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cá trê làm sạch, cắt khúc vừa ăn",
      "Bước 2: Ướp cá với muối, tiêu, nước mắm, tỏi băm",
      "Bước 3: Pha bột chiên với nước lạnh, thêm trứng",
      "Bước 4: Nhúng cá vào bột, chiên trong dầu nóng",
      "Bước 5: Chiên đến khi vàng giòn, vớt ra giấy thấm dầu",
      "Bước 6: Dùng với rau sống và nước chấm chua ngọt",
    ],
    ingredients: [
      { ingredientName: "Cá lóc", grams: 200 },
      { ingredientName: "Bột mì", grams: 40 },
      { ingredientName: "Trứng gà", grams: 50 },
      { ingredientName: "Dầu ăn", grams: 20 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Tỏi", grams: 5 },
    ],
  },
  {
    nameVi: "Cháo lòng",
    regionCode: "southern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 450,
    calories: 380,
    proteinG: 22,
    carbsG: 42,
    fatG: 14,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 60,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Lòng heo làm sạch với muối và gừng, luộc chín",
      "Bước 2: Ninh xương lấy nước dùng nấu cháo",
      "Bước 3: Vo gạo nấu cháo với nước ninh xương",
      "Bước 4: Thái lòng heo thành miếng nhỏ vừa ăn",
      "Bước 5: Rắc hành lá, tiêu, gừng sợi lên tô cháo",
      "Bước 6: Dùng với quẩy và rau thơm",
    ],
    ingredients: [
      { ingredientName: "Gạo trắng", grams: 100 },
      { ingredientName: "Thịt heo nạc", grams: 80 },
      { ingredientName: "Gừng", grams: 15 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Dầu ăn", grams: 10 },
    ],
  },

  // ======= SIDE DISHES (15) =======
  {
    nameVi: "Rau muống xào tỏi",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 90,
    proteinG: 4,
    carbsG: 6,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Rau muống nhặt bỏ lá già, cắt khúc, rửa sạch",
      "Bước 2: Tỏi băm nhỏ, phi thơm với dầu ăn",
      "Bước 3: Cho rau muống vào xào lửa lớn, đảo nhanh tay",
      "Bước 4: Nêm nước mắm, muối cho vừa ăn",
      "Bước 5: Tắt bếp, bày ra dĩa",
    ],
    ingredients: [
      { ingredientName: "Rau muống", grams: 200 },
      { ingredientName: "Tỏi", grams: 10 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Nước mắm", grams: 5 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Công thức gỏi đu đủ tai heo",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 180,
    proteinG: 14,
    carbsG: 12,
    fatG: 8,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: tai heo làm sạch, luộc chín, thái mỏng",
      "Bước 2: đu đủ xanh bào sợi, ngâm nước muối loãng",
      "Bước 3: pha nước mắm chua ngọt với chanh, tỏi, ớt",
      "Bước 4: trộn tai heo, đu đủ, cà rốt với nước mắm",
      "Bước 5: rắc đậu phộng rang và rau thơm lên trên",
    ],
    ingredients: [
      { ingredientName: "Đu đủ", grams: 100 },
      { ingredientName: "Thịt heo nạc", grams: 80 },
      { ingredientName: "Cà rốt", grams: 50 },
      { ingredientName: "Nước mắm", grams: 20 },
      { ingredientName: "Chanh", grams: 15 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Tỏi", grams: 5 },
    ],
  },
  {
    nameVi: "Dưa leo trộn thính",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 80,
    proteinG: 3,
    carbsG: 10,
    fatG: 3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Dưa leo rửa sạch, đập dập, cắt miếng vừa ăn",
      "Bước 2: Làm thính từ gạo rang hoặc mua sẵn",
      "Bước 3: Trộn dưa leo với thính, muối, đường, chanh",
      "Bước 4: Thêm hành phi và ớt tỏi băm",
      "Bước 5: Bày lên dĩa, dùng kèm với món mặn",
    ],
    ingredients: [
      { ingredientName: "Dưa leo", grams: 150 },
      { ingredientName: "Gạo trắng", grams: 15 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Ớt", grams: 3 },
    ],
  },
  {
    nameVi: "Cà tím nướng mỡ hành",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 110,
    proteinG: 3,
    carbsG: 10,
    fatG: 7,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cà tím rửa sạch, nướng trên than hồng hoặc lò nướng",
      "Bước 2: Lột vỏ cà tím chín, xé hoặc cắt miếng",
      "Bước 3: Phi hành tím với dầu ăn cho thơm",
      "Bước 4: Rưới mỡ hành lên cà tím",
      "Bước 5: Rắc muối tiêu chanh và ớt bột",
    ],
    ingredients: [
      { ingredientName: "Cà tím", grams: 200 },
      { ingredientName: "Dầu ăn", grams: 10 },
      { ingredientName: "Hành tím", grams: 10 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Ớt bột", grams: 2 },
    ],
  },
  {
    nameVi: "Bông cải xanh luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 55,
    proteinG: 4,
    carbsG: 8,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bông cải xanh cắt miếng vừa ăn, rửa sạch",
      "Bước 2: Đun sôi nước với một ít muối",
      "Bước 3: Cho bông cải vào luộc 3-5 phút",
      "Bước 4: Vớt ra thau nước đá để giữ màu xanh",
      "Bước 5: Dùng với muối tiêu chanh hoặc nước mắm",
    ],
    ingredients: [
      { ingredientName: "Bông cải xanh", grams: 200 },
      { ingredientName: "Muối", grams: 3 },
    ],
  },
  {
    nameVi: "Cải bẹ xanh luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 40,
    proteinG: 3,
    carbsG: 6,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cải bẹ xanh nhặt rửa sạch, cắt khúc",
      "Bước 2: Đun sôi nước với muối",
      "Bước 3: Cho cải vào luộc đến khi mềm",
      "Bước 4: Vớt ra dĩa, để ráo nước",
      "Bước 5: Dùng với nước mắm tỏi ớt",
    ],
    ingredients: [
      { ingredientName: "Cải bẹ xanh", grams: 200 },
      { ingredientName: "Muối", grams: 3 },
      { ingredientName: "Nước mắm", grams: 5 },
    ],
  },
  {
    nameVi: "Đậu bắp luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 45,
    proteinG: 3,
    carbsG: 7,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu bắp rửa sạch, cắt bỏ cuống",
      "Bước 2: Đun sôi nước với muối",
      "Bước 3: Luộc đậu bắp 3-4 phút đến khi chín tới",
      "Bước 4: Vớt ra dĩa, để nguội bớt",
      "Bước 5: Dùng với muối tiêu chanh hoặc nước mắm",
    ],
    ingredients: [
      { ingredientName: "Đậu bắp", grams: 150 },
      { ingredientName: "Muối", grams: 3 },
    ],
  },
  {
    nameVi: "Rau ngót luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 180,
    calories: 45,
    proteinG: 4,
    carbsG: 5,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Rau ngót rửa sạch, để ráo",
      "Bước 2: Đun sôi nước, thêm một ít muối",
      "Bước 3: Cho rau ngót vào luộc nhanh 3 phút",
      "Bước 4: Vớt ra dĩa, không đậy nắp để giữ màu xanh",
      "Bước 5: Dùng với nước mắm hoặc muối tiêu",
    ],
    ingredients: [
      { ingredientName: "Rau ngót", grams: 180 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Đậu phụ chiên sả ớt",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 180,
    calories: 200,
    proteinG: 10,
    carbsG: 6,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu phụ cắt miếng vừa ăn",
      "Bước 2: Sả và ớt băm nhỏ",
      "Bước 3: Ướp đậu phụ với sả, ớt, muối, nước mắm",
      "Bước 4: Chiên đậu trong dầu nóng đến khi vàng đều",
      "Bước 5: Vớt ra giấy thấm dầu, dùng nóng",
    ],
    ingredients: [
      { ingredientName: "Đậu phụ", grams: 150 },
      { ingredientName: "Sả", grams: 15 },
      { ingredientName: "Ớt", grams: 5 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Nước mắm", grams: 5 },
    ],
  },
  {
    nameVi: "Mồng tơi luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 35,
    proteinG: 3,
    carbsG: 5,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Mồng tơi nhặt lá, rửa sạch",
      "Bước 2: Đun sôi nước với muối",
      "Bước 3: Cho mồng tơi vào luộc nhanh 2-3 phút",
      "Bước 4: Vớt ra dĩa, để ráo",
      "Bước 5: Dùng với nước mắm tỏi ớt",
    ],
    ingredients: [
      { ingredientName: "Mồng tơi", grams: 200 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Nộm bắp cải cà rốt",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 180,
    calories: 70,
    proteinG: 2,
    carbsG: 10,
    fatG: 3,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bắp cải và cà rốt bào sợi mỏng",
      "Bước 2: Pha nước mắm chua ngọt với chanh, đường, tỏi, ớt",
      "Bước 3: Trộn bắp cải, cà rốt với nước mắm",
      "Bước 4: Rắc lạc rang lên trên",
      "Bước 5: Bày ra dĩa, thêm rau thơm",
    ],
    ingredients: [
      { ingredientName: "Bắp cải", grams: 100 },
      { ingredientName: "Cà rốt", grams: 60 },
      { ingredientName: "Nước mắm", grams: 15 },
      { ingredientName: "Chanh", grams: 10 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Đường", grams: 5 },
    ],
  },
  {
    nameVi: "Khoai lang luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 170,
    proteinG: 3,
    carbsG: 38,
    fatG: 1,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Khoai lang rửa sạch đất",
      "Bước 2: Nấu nước sôi, cho khoai lang vào luộc",
      "Bước 3: Luộc đến khi khoai mềm, dùng tăm thử",
      "Bước 4: Vớt ra để nguội bớt",
      "Bước 5: Lột vỏ và dùng",
    ],
    ingredients: [
      { ingredientName: "Khoai lang", grams: 200 },
    ],
  },
  {
    nameVi: "Ngô luộc",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 trái",
    servingGrams: 200,
    calories: 180,
    proteinG: 5,
    carbsG: 38,
    fatG: 2,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bóc vỏ ngô, giữ lại lớp vỏ mỏng bên trong",
      "Bước 2: Ngâm ngô trong nước muối loãng 10 phút",
      "Bước 3: Đun sôi nước, cho ngô vào luộc",
      "Bước 4: Luộc 20 phút đến khi ngô chín đều",
      "Bước 5: Vớt ra ráo nước, dùng nóng",
    ],
    ingredients: [
      { ingredientName: "Ngô", grams: 200 },
    ],
  },
  {
    nameVi: "Cá hồi áp chảo",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 phần",
    servingGrams: 150,
    calories: 280,
    proteinG: 24,
    carbsG: 2,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Cá hồi rửa sạch, thấm khô, ướp muối tiêu",
      "Bước 2: Đun nóng dầu olive trong chảo chống dính",
      "Bước 3: Áp chảo cá hồi mặt da xuống trước 4 phút",
      "Bước 4: Lật mặt cá, áp chảo thêm 3 phút",
      "Bước 5: Bày ra dĩa, dùng với chanh và rau sống",
    ],
    ingredients: [
      { ingredientName: "Cá hồi", grams: 150 },
      { ingredientName: "Dầu olive", grams: 10 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Chanh", grams: 10 },
    ],
  },
  {
    nameVi: "Súp bí đỏ",
    regionCode: "southern",
    categorySlug: "side-dish",
    servingSize: "1 tô",
    servingGrams: 300,
    calories: 130,
    proteinG: 4,
    carbsG: 22,
    fatG: 4,
    mealTime: ["breakfast", "lunch", "dinner"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bí đỏ gọt vỏ, cắt miếng nhỏ",
      "Bước 2: Nấu bí đỏ với nước dùng đến khi mềm",
      "Bước 3: Xay nhuyễn hỗn hợp bí đỏ",
      "Bước 4: Nêm muối, tiêu, một ít sữa tươi",
      "Bước 5: Đun sôi lại, cho ra tô, rắc hành",
    ],
    ingredients: [
      { ingredientName: "Bí đỏ", grams: 200 },
      { ingredientName: "Sữa tươi", grams: 50 },
      { ingredientName: "Muối", grams: 2 },
      { ingredientName: "Hành lá", grams: 5 },
    ],
  },

  // ======= SNACKS (15) =======
  {
    nameVi: "Bánh tráng trộn",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 tô",
    servingGrams: 150,
    calories: 250,
    proteinG: 6,
    carbsG: 30,
    fatG: 12,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bánh tráng cắt sợi vừa ăn",
      "Bước 2: Luộc tôm chín, bóc vỏ, băm nhỏ",
      "Bước 3: Pha nước sốt từ nước mắm, chanh, đường, ớt",
      "Bước 4: Trộn bánh tráng với tôm, khô bò, xoài bào sợi",
      "Bước 5: Rắc lạc rang, hành phi, rau răm lên trên",
    ],
    ingredients: [
      { ingredientName: "Bánh tráng", grams: 80 },
      { ingredientName: "Tôm", grams: 20 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Xoài", grams: 30 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Chanh", grams: 10 },
    ],
  },
  {
    nameVi: "Bánh phồng tôm",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "100 gram",
    servingGrams: 100,
    calories: 340,
    proteinG: 8,
    carbsG: 52,
    fatG: 12,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bắc chảo dầu nóng già",
      "Bước 2: Thả bánh phồng tôm vào chiên từng cái",
      "Bước 3: Khi bánh nở phồng đều, lật mặt",
      "Bước 4: Vớt ra giấy thấm dầu",
      "Bước 5: Để nguội, dùng với tương ớt",
    ],
    ingredients: [
      { ingredientName: "Bánh phồng", grams: 100 },
      { ingredientName: "Dầu ăn", grams: 20 },
    ],
  },
  {
    nameVi: "Chè đậu xanh nước cốt dừa",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 250,
    calories: 280,
    proteinG: 8,
    carbsG: 44,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu xanh vo sạch, ngâm nước 2 tiếng",
      "Bước 2: Nấu đậu xanh với nước đến khi mềm nát",
      "Bước 3: Thêm đường khuấy đều cho tan",
      "Bước 4: Vắt nước cốt dừa hòa với bột sắn dây",
      "Bước 5: Đổ nước cốt dừa lên trên, dùng nóng hoặc lạnh",
    ],
    ingredients: [
      { ingredientName: "Đậu xanh", grams: 80 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Bột sắn dây", grams: 10 },
    ],
  },
  {
    nameVi: "Bánh bò",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "5 cái",
    servingGrams: 150,
    calories: 260,
    proteinG: 4,
    carbsG: 44,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Trộn bột gạo, bột mì, đường, men nở với nước cốt dừa",
      "Bước 2: Ủ bột 2 tiếng cho nở",
      "Bước 3: Đổ bột vào khuôn nhỏ hấp chín",
      "Bước 4: Hấp bánh 15 phút đến khi chín",
      "Bước 5: Lấy bánh ra, để nguội, dùng kèm dừa nạo",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Bột mì", grams: 30 },
      { ingredientName: "Dừa", grams: 50 },
      { ingredientName: "Đường", grams: 25 },
      { ingredientName: "Gia vị", grams: 2 },
    ],
  },
  {
    nameVi: "Kem bơ sữa đặc",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 ly",
    servingGrams: 200,
    calories: 280,
    proteinG: 4,
    carbsG: 30,
    fatG: 16,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bơ chín cắt đôi, bỏ hạt, lấy thịt",
      "Bước 2: Cho bơ, sữa đặc, đá bào vào máy xay",
      "Bước 3: Xay nhuyễn mịn",
      "Bước 4: Rót ra ly, rắc một ít dừa nạo",
      "Bước 5: Dùng ngay lạnh",
    ],
    ingredients: [
      { ingredientName: "Bơ", grams: 100 },
      { ingredientName: "Sữa đặc", grams: 30 },
      { ingredientName: "Sữa tươi", grams: 50 },
    ],
  },
  {
    nameVi: "Chè bưởi miền Nam",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 chén",
    servingGrams: 250,
    calories: 260,
    proteinG: 4,
    carbsG: 42,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 30,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Cùi bưởi cắt hạt lựu, luộc với nước phèn chua",
      "Bước 2: Xả nước lạnh nhiều lần cho hết đắng",
      "Bước 3: Nấu nước cốt dừa với đường và chút muối",
      "Bước 4: Hòa bột sắn dây tạo độ sánh",
      "Bước 5: Thêm cùi bưởi, đậu xanh đã nấu chín",
      "Bước 6: Rắc mè rang lên khi dùng",
    ],
    ingredients: [
      { ingredientName: "Bưởi", grams: 80 },
      { ingredientName: "Đậu xanh", grams: 50 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Đường", grams: 25 },
      { ingredientName: "Bột sắn dây", grams: 10 },
    ],
  },
  {
    nameVi: "Bột chiên",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 320,
    proteinG: 6,
    carbsG: 40,
    fatG: 16,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Pha bột mì với nước, muối, hành lá",
      "Bước 2: Hấp bột đến khi chín, để nguội cắt miếng",
      "Bước 3: Chiên bột trong chảo dầu nóng",
      "Bước 4: Đập trứng lên trên khi bột vàng",
      "Bước 5: Dùng với tương ớt và nước mắm chua ngọt",
    ],
    ingredients: [
      { ingredientName: "Bột mì", grams: 100 },
      { ingredientName: "Trứng gà", grams: 50 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Hành lá", grams: 10 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Chè ba màu",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 310,
    proteinG: 6,
    carbsG: 52,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Nấu đậu đỏ, đậu xanh riêng với đường đến khi mềm",
      "Bước 2: Nấu thạch lá dứa cắt hạt lựu",
      "Bước 3: Khoai môn cắt hạt lựu, hấp chín",
      "Bước 4: Pha nước cốt dừa với đường và chút muối",
      "Bước 5: Xếp từng lớp vào ly: đậu, thạch, khoai môn",
      "Bước 6: Đổ nước cốt dừa và đá bào lên trên",
    ],
    ingredients: [
      { ingredientName: "Đậu đen", grams: 50 },
      { ingredientName: "Đậu xanh", grams: 40 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Bột sắn dây", grams: 10 },
      { ingredientName: "Khoai mì", grams: 50 },
    ],
  },
  {
    nameVi: "Gỏi xoài khô bò",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 150,
    calories: 200,
    proteinG: 12,
    carbsG: 18,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Xoài xanh bào sợi dài",
      "Bước 2: Xé khô bò thành sợi nhỏ",
      "Bước 3: Pha nước mắm chua ngọt với tỏi, ớt",
      "Bước 4: Trộn xoài và khô bò với nước sốt",
      "Bước 5: Rắc lạc rang và rau răm",
    ],
    ingredients: [
      { ingredientName: "Xoài", grams: 80 },
      { ingredientName: "Thịt bò", grams: 40 },
      { ingredientName: "Lạc", grams: 15 },
      { ingredientName: "Nước mắm", grams: 10 },
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Ớt", grams: 3 },
    ],
  },
  {
    nameVi: "Mít sấy",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "100 gram",
    servingGrams: 100,
    calories: 280,
    proteinG: 4,
    carbsG: 60,
    fatG: 2,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 60,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Mít tách múi, bỏ hạt",
      "Bước 2: Xếp mít lên khay sấy có lót giấy nến",
      "Bước 3: Sấy mít ở nhiệt độ 60-70 độ C",
      "Bước 4: Sấy đến khi mít dẻo và không còn dính",
      "Bước 5: Để nguội, bảo quản trong hũ kín",
    ],
    ingredients: [
      { ingredientName: "Mít", grams: 200 },
    ],
  },
  {
    nameVi: "Bánh da lợn",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "5 miếng",
    servingGrams: 200,
    calories: 300,
    proteinG: 4,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Trộn bột với nước cốt dừa, đường, muối, lá dứa xay",
      "Bước 2: Chia bột làm 2 phần: 1 phần nhuộm lá dứa, 1 phần nhuộm gấc",
      "Bước 3: Hấp từng lớp mỏng, chờ lớp trước chín mới đổ lớp sau",
      "Bước 4: Hấp đến khi hết bột, bánh chín đều",
      "Bước 5: Để nguội, cắt miếng vừa ăn",
    ],
    ingredients: [
      { ingredientName: "Bột gạo", grams: 80 },
      { ingredientName: "Bột mì", grams: 30 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Đường", grams: 30 },
      { ingredientName: "Gia vị", grams: 2 },
    ],
  },
  {
    nameVi: "Bắp rang bơ",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 tô",
    servingGrams: 80,
    calories: 180,
    proteinG: 3,
    carbsG: 28,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bắc chảo sâu lòng lên bếp",
      "Bước 2: Cho bơ vào chảo đun chảy",
      "Bước 3: Thả ngô vào chảo, đậy nắp",
      "Bước 4: Lắc chảo đều tay đến khi ngô nổ hết",
      "Bước 5: Đổ ra tô, thêm muối hoặc đường",
    ],
    ingredients: [
      { ingredientName: "Ngô", grams: 80 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },
  {
    nameVi: "Sữa chua nếp cẩm",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 240,
    proteinG: 6,
    carbsG: 40,
    fatG: 6,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    difficulty: "medium",
    recipeSteps: [
      "Bước 1: Nếp cẩm vo sạch, ngâm nước qua đêm",
      "Bước 2: Nấu nếp cẩm với nước đến khi nở mềm",
      "Bước 3: Thêm đường vào nếp cẩm, khuấy đều",
      "Bước 4: Để nếp cẩm nguội, múc vào ly",
      "Bước 5: Đổ sữa chua lên trên, thêm đá bào",
    ],
    ingredients: [
      { ingredientName: "Nếp", grams: 60 },
      { ingredientName: "Sữa chua", grams: 100 },
      { ingredientName: "Đường", grams: 20 },
      { ingredientName: "Sữa tươi", grams: 50 },
    ],
  },
  {
    nameVi: "Chuối chiên",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "5 miếng",
    servingGrams: 150,
    calories: 320,
    proteinG: 3,
    carbsG: 48,
    fatG: 14,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Chuối chín lột vỏ, cắt lát dọc",
      "Bước 2: Pha bột mì với nước, đường, muối, vừng",
      "Bước 3: Nhúng lát chuối vào bột",
      "Bước 4: Chiên trong dầu nóng đến khi vàng giòn",
      "Bước 5: Vớt ra giấy thấm dầu, dùng nóng",
    ],
    ingredients: [
      { ingredientName: "Chuối", grams: 100 },
      { ingredientName: "Bột mì", grams: 40 },
      { ingredientName: "Dầu ăn", grams: 15 },
      { ingredientName: "Đường", grams: 10 },
      { ingredientName: "Vừng", grams: 5 },
    ],
  },
  {
    nameVi: "Khoai mì hấp nước cốt dừa",
    regionCode: "southern",
    categorySlug: "snacks",
    servingSize: "1 dĩa",
    servingGrams: 200,
    calories: 260,
    proteinG: 3,
    carbsG: 42,
    fatG: 8,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Khoai mì lột vỏ, cắt khúc, ngâm nước muối",
      "Bước 2: Hấp khoai mì đến khi mềm",
      "Bước 3: Nấu nước cốt dừa với đường và chút muối",
      "Bước 4: Xếp khoai mì ra dĩa",
      "Bước 5: Rưới nước cốt dừa và rắc mè rang",
    ],
    ingredients: [
      { ingredientName: "Khoai mì", grams: 150 },
      { ingredientName: "Dừa", grams: 60 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Muối", grams: 2 },
    ],
  },

  // ======= DRINKS (5) =======
  {
    nameVi: "Nước dừa tươi",
    regionCode: "southern",
    categorySlug: "drinks",
    servingSize: "1 trái",
    servingGrams: 300,
    calories: 50,
    proteinG: 1,
    carbsG: 8,
    fatG: 1,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Chọn dừa xiêm tươi còn vỏ xanh",
      "Bước 2: Dùng dao chặt một đầu quả dừa",
      "Bước 3: Để nguyên trái hoặc đổ ra ly",
      "Bước 4: Thêm đá viên nếu thích uống lạnh",
    ],
    ingredients: [
      { ingredientName: "Dừa xiêm", grams: 300 },
    ],
  },
  {
    nameVi: "Sinh tố bơ dừa",
    regionCode: "southern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 220,
    proteinG: 4,
    carbsG: 24,
    fatG: 12,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Bơ chín cắt đôi, bỏ hạt",
      "Bước 2: Nạo dừa tươi lấy nước cốt",
      "Bước 3: Cho bơ, nước cốt dừa, sữa đặc vào máy xay",
      "Bước 4: Thêm đá bào, xay nhuyễn mịn",
      "Bước 5: Rót ra ly, thêm dừa nạo lên mặt",
    ],
    ingredients: [
      { ingredientName: "Bơ", grams: 100 },
      { ingredientName: "Dừa", grams: 80 },
      { ingredientName: "Sữa đặc", grams: 20 },
      { ingredientName: "Sữa tươi", grams: 50 },
    ],
  },
  {
    nameVi: "Nước mía",
    regionCode: "southern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 120,
    proteinG: 1,
    carbsG: 30,
    fatG: 0,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Mía tươi rửa sạch, lột vỏ",
      "Bước 2: Cắt mía thành khúc ngắn vừa ép",
      "Bước 3: Cho mía vào máy ép lấy nước",
      "Bước 4: Thêm nước cốt chanh và đá viên",
    ],
    ingredients: [
      { ingredientName: "Đường", grams: 5 },
      { ingredientName: "Chanh", grams: 15 },
    ],
  },
  {
    nameVi: "Chanh dây (chanh leo) uống",
    regionCode: "southern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 80,
    proteinG: 1,
    carbsG: 16,
    fatG: 1,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Chanh dây cắt đôi, lấy ruột",
      "Bước 2: Lọc ruột chanh dây lấy nước cốt",
      "Bước 3: Pha nước ấm với đường hoặc mật ong",
      "Bước 4: Thêm nước cốt chanh dây và đá",
    ],
    ingredients: [
      { ingredientName: "Chanh", grams: 50 },
      { ingredientName: "Đường", grams: 15 },
      { ingredientName: "Mật ong", grams: 10 },
    ],
  },
  {
    nameVi: "Sữa đậu nành nóng",
    regionCode: "southern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 110,
    proteinG: 6,
    carbsG: 14,
    fatG: 4,
    mealTime: ["breakfast", "lunch"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: "easy",
    recipeSteps: [
      "Bước 1: Đậu nành ngâm nước qua đêm, vo sạch",
      "Bước 2: Xay đậu nành với nước lọc",
      "Bước 3: Lọc bã lấy nước đậu",
      "Bước 4: Đun sôi nước đậu, thêm đường",
      "Bước 5: Rót ra ly, dùng nóng hoặc lạnh",
    ],
    ingredients: [
      { ingredientName: "Đậu nành", grams: 60 },
      { ingredientName: "Đường", grams: 15 },
    ],
  },
]

export async function seedFoodsMoreSouthern(prisma: PrismaClient) {
  const regions = await prisma.region.findMany()
  const categories = await prisma.category.findMany()
  const regionMap = Object.fromEntries(regions.map(r => [r.code, r.id]))
  const categoryMap = Object.fromEntries(categories.map(c => [c.slug, c.id]))

  for (const f of foods) {
    const foodData = {
      id: f.nameVi,
      nameVi: f.nameVi,
      servingSize: f.servingSize,
      servingGrams: f.servingGrams,
      calories: f.calories,
      proteinG: f.proteinG,
      carbsG: f.carbsG,
      fatG: f.fatG,
      mealTime: f.mealTime,
      recipeSteps: f.recipeSteps ?? [],
      prepTimeMinutes: f.prepTimeMinutes ?? null,
      cookTimeMinutes: f.cookTimeMinutes ?? null,
      difficulty: f.difficulty ?? null,
      isVerified: true,
      regionId: regionMap[f.regionCode],
      categoryId: categoryMap[f.categorySlug],
    }

    await prisma.food.upsert({
      where: { id: f.nameVi },
      update: foodData,
      create: {
        ...foodData,
        ingredients: {
          create: (f.ingredients ?? []).map(ing => ({
            ingredientName: ing.ingredientName,
            grams: ing.grams,
            proteinG: 0,
            carbsG: 0,
            fatG: 0,
          })),
        },
      },
    })
  }
  console.log(`✅ Seeded ${foods.length} southern dishes (more)`)
}
