import { PrismaClient } from "../../src/generated/prisma"

const foods = [
  { nameVi: "Bún bò Huế", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 450, proteinG: 25, carbsG: 50, fatG: 15, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bún bò chả", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 480, proteinG: 28, carbsG: 52, fatG: 16, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bún thịt nướng Huế", categorySlug: "main-dish", servingSize: "1 dĩa (350g)", servingGrams: 350, calories: 520, proteinG: 22, carbsG: 65, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Mì Quảng gà", categorySlug: "main-dish", servingSize: "1 tô (350g)", servingGrams: 350, calories: 420, proteinG: 24, carbsG: 48, fatG: 14, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Mì Quảng tôm", categorySlug: "main-dish", servingSize: "1 tô (350g)", servingGrams: 350, calories: 380, proteinG: 20, carbsG: 45, fatG: 12, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Mì Quảng mực", categorySlug: "main-dish", servingSize: "1 tô (350g)", servingGrams: 350, calories: 360, proteinG: 18, carbsG: 44, fatG: 11, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Cao lầu Hội An", categorySlug: "main-dish", servingSize: "1 tô (350g)", servingGrams: 350, calories: 450, proteinG: 20, carbsG: 55, fatG: 16, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cơm hến", categorySlug: "main-dish", servingSize: "1 tô (300g)", servingGrams: 300, calories: 280, proteinG: 15, carbsG: 40, fatG: 6, mealTime: ["lunch", "dinner"] },
  { nameVi: "Chè hến", categorySlug: "main-dish", servingSize: "1 tô (300g)", servingGrams: 300, calories: 200, proteinG: 12, carbsG: 28, fatG: 4, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh canh Nam Phổ", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 380, proteinG: 18, carbsG: 55, fatG: 8, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bánh canh cá lóc", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 360, proteinG: 20, carbsG: 50, fatG: 7, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bánh canh tôm", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 350, proteinG: 18, carbsG: 48, fatG: 8, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bánh bèo Huế", categorySlug: "snacks", servingSize: "1 dĩa (8-10 cái)", servingGrams: 200, calories: 220, proteinG: 6, carbsG: 35, fatG: 6, mealTime: ["snack"] },
  { nameVi: "Bánh nậm", categorySlug: "snacks", servingSize: "1 dĩa (4 cái)", servingGrams: 150, calories: 180, proteinG: 5, carbsG: 30, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Bánh lọc", categorySlug: "snacks", servingSize: "1 dĩa (6-8 cái)", servingGrams: 150, calories: 200, proteinG: 5, carbsG: 32, fatG: 5, mealTime: ["snack"] },
  { nameVi: "Bánh ướt thịt nướng", categorySlug: "main-dish", servingSize: "1 dĩa (250g)", servingGrams: 250, calories: 350, proteinG: 16, carbsG: 42, fatG: 12, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh lọt", categorySlug: "snacks", servingSize: "1 chén (150g)", servingGrams: 150, calories: 150, proteinG: 2, carbsG: 30, fatG: 2, mealTime: ["snack"] },
  { nameVi: "Bánh đúc", categorySlug: "snacks", servingSize: "1 dĩa (200g)", servingGrams: 200, calories: 180, proteinG: 4, carbsG: 32, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Nem lụi Huế", categorySlug: "main-dish", servingSize: "1 dĩa (5 que)", servingGrams: 200, calories: 350, proteinG: 20, carbsG: 25, fatG: 18, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Chả Huế", categorySlug: "side-dish", servingSize: "1 phần (100g)", servingGrams: 100, calories: 200, proteinG: 15, carbsG: 5, fatG: 14, mealTime: ["snack"] },
  { nameVi: "Chả bò", categorySlug: "side-dish", servingSize: "1 phần (100g)", servingGrams: 100, calories: 220, proteinG: 18, carbsG: 3, fatG: 15, mealTime: ["snack"] },
  { nameVi: "Chả cua", categorySlug: "side-dish", servingSize: "1 phần (100g)", servingGrams: 100, calories: 180, proteinG: 14, carbsG: 6, fatG: 11, mealTime: ["snack"] },
  { nameVi: "Nem chua Huế", categorySlug: "snacks", servingSize: "2 cái (50g)", servingGrams: 50, calories: 80, proteinG: 6, carbsG: 4, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Tré Huế", categorySlug: "snacks", servingSize: "1 phần (80g)", servingGrams: 80, calories: 120, proteinG: 8, carbsG: 6, fatG: 7, mealTime: ["snack"] },
  { nameVi: "Thịt heo ngâm mắm", categorySlug: "side-dish", servingSize: "1 phần (80g)", servingGrams: 80, calories: 150, proteinG: 12, carbsG: 3, fatG: 10, mealTime: ["snack"] },
  { nameVi: "Cơm sườn non", categorySlug: "main-dish", servingSize: "1 dĩa (400g)", servingGrams: 400, calories: 600, proteinG: 28, carbsG: 70, fatG: 20, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cơm gà Hội An", categorySlug: "main-dish", servingSize: "1 dĩa (400g)", servingGrams: 400, calories: 580, proteinG: 30, carbsG: 65, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cơm tấm Đà Nẵng", categorySlug: "main-dish", servingSize: "1 dĩa (400g)", servingGrams: 400, calories: 560, proteinG: 26, carbsG: 72, fatG: 16, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cơm dừa", categorySlug: "main-dish", servingSize: "1 dĩa (350g)", servingGrams: 350, calories: 480, proteinG: 10, carbsG: 55, fatG: 24, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cơm hấp lá sen", categorySlug: "main-dish", servingSize: "1 phần (350g)", servingGrams: 350, calories: 420, proteinG: 18, carbsG: 55, fatG: 12, mealTime: ["lunch", "dinner"] },
  { nameVi: "Mực nhồi thịt", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 240, proteinG: 22, carbsG: 8, fatG: 13, mealTime: ["lunch", "dinner"] },
  { nameVi: "Mực chiên bột", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 280, proteinG: 16, carbsG: 18, fatG: 15, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Cá nục hấp", categorySlug: "main-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 180, proteinG: 22, carbsG: 1, fatG: 10, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cá nục kho", categorySlug: "main-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 200, proteinG: 22, carbsG: 4, fatG: 11, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cá nục chiên", categorySlug: "main-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 250, proteinG: 20, carbsG: 2, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cá thu kho", categorySlug: "main-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 240, proteinG: 24, carbsG: 3, fatG: 14, mealTime: ["lunch", "dinner"] },
  { nameVi: "Tôm hấp bia", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 180, proteinG: 24, carbsG: 2, fatG: 8, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Tôm nướng muối ớt", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 200, proteinG: 25, carbsG: 3, fatG: 9, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Tôm chiên xù", categorySlug: "main-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 280, proteinG: 18, carbsG: 15, fatG: 16, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Ghẹ hấp", categorySlug: "main-dish", servingSize: "1 phần (300g)", servingGrams: 300, calories: 160, proteinG: 22, carbsG: 1, fatG: 7, mealTime: ["lunch", "dinner"] },
  { nameVi: "Ghẹ rang me", categorySlug: "main-dish", servingSize: "1 phần (300g)", servingGrams: 300, calories: 220, proteinG: 20, carbsG: 8, fatG: 12, mealTime: ["lunch", "dinner"] },
  { nameVi: "Ốc hương xào bơ", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 250, proteinG: 16, carbsG: 6, fatG: 18, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Ốc giác xào dừa", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 240, proteinG: 14, carbsG: 8, fatG: 17, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Sò huyết rang me", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 180, proteinG: 18, carbsG: 8, fatG: 8, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Sò lông hấp", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 140, proteinG: 16, carbsG: 3, fatG: 6, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Bê thui Cầu Mống", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 280, proteinG: 26, carbsG: 5, fatG: 17, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bò nhúng mẻ", categorySlug: "main-dish", servingSize: "1 phần (250g)", servingGrams: 250, calories: 300, proteinG: 28, carbsG: 6, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bò bảy món", categorySlug: "main-dish", servingSize: "1 phần (350g)", servingGrams: 350, calories: 500, proteinG: 38, carbsG: 15, fatG: 30, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bò nướng lá lốt", categorySlug: "main-dish", servingSize: "1 dĩa (8 cuốn)", servingGrams: 200, calories: 320, proteinG: 24, carbsG: 8, fatG: 20, mealTime: ["lunch", "dinner", "snack"] },
  { nameVi: "Lẩu cá mú", categorySlug: "main-dish", servingSize: "1 phần (500g)", servingGrams: 500, calories: 350, proteinG: 28, carbsG: 15, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Lẩu tôm chua", categorySlug: "main-dish", servingSize: "1 phần (500g)", servingGrams: 500, calories: 320, proteinG: 22, carbsG: 18, fatG: 16, mealTime: ["lunch", "dinner"] },
  { nameVi: "Lẩu gà lá é", categorySlug: "main-dish", servingSize: "1 phần (500g)", servingGrams: 500, calories: 340, proteinG: 26, carbsG: 14, fatG: 18, mealTime: ["lunch", "dinner"] },
  { nameVi: "Lẩu bò nhúng dấm", categorySlug: "main-dish", servingSize: "1 phần (500g)", servingGrams: 500, calories: 380, proteinG: 30, carbsG: 12, fatG: 22, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bún hến", categorySlug: "main-dish", servingSize: "1 tô (350g)", servingGrams: 350, calories: 280, proteinG: 14, carbsG: 42, fatG: 6, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bún cá rô", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 380, proteinG: 18, carbsG: 50, fatG: 10, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bún tôm", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 360, proteinG: 16, carbsG: 48, fatG: 10, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Bún thịt heo quay", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 480, proteinG: 20, carbsG: 52, fatG: 20, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Xôi đậu phộng", categorySlug: "main-dish", servingSize: "1 phần (250g)", servingGrams: 250, calories: 420, proteinG: 12, carbsG: 60, fatG: 14, mealTime: ["breakfast"] },
  { nameVi: "Xôi bắp", categorySlug: "main-dish", servingSize: "1 phần (250g)", servingGrams: 250, calories: 380, proteinG: 8, carbsG: 65, fatG: 10, mealTime: ["breakfast"] },
  { nameVi: "Xôi gà Hội An", categorySlug: "main-dish", servingSize: "1 phần (300g)", servingGrams: 300, calories: 480, proteinG: 20, carbsG: 58, fatG: 18, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Chè bắp Huế", categorySlug: "snacks", servingSize: "1 chén (200g)", servingGrams: 200, calories: 180, proteinG: 3, carbsG: 38, fatG: 2, mealTime: ["snack"] },
  { nameVi: "Chè đậu ván", categorySlug: "snacks", servingSize: "1 chén (200g)", servingGrams: 200, calories: 220, proteinG: 8, carbsG: 38, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Chè khoai sọ", categorySlug: "snacks", servingSize: "1 chén (200g)", servingGrams: 200, calories: 200, proteinG: 2, carbsG: 40, fatG: 3, mealTime: ["snack"] },
  { nameVi: "Chè hạt sen", categorySlug: "snacks", servingSize: "1 chén (200g)", servingGrams: 200, calories: 180, proteinG: 5, carbsG: 35, fatG: 2, mealTime: ["snack"] },
  { nameVi: "Chè sắn", categorySlug: "snacks", servingSize: "1 chén (200g)", servingGrams: 200, calories: 220, proteinG: 1, carbsG: 45, fatG: 3, mealTime: ["snack"] },
  { nameVi: "Rau câu dừa", categorySlug: "snacks", servingSize: "1 phần (150g)", servingGrams: 150, calories: 120, proteinG: 1, carbsG: 20, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Rau câu lá dứa", categorySlug: "snacks", servingSize: "1 phần (150g)", servingGrams: 150, calories: 100, proteinG: 1, carbsG: 22, fatG: 1, mealTime: ["snack"] },
  { nameVi: "Rau câu sữa chua", categorySlug: "snacks", servingSize: "1 phần (150g)", servingGrams: 150, calories: 130, proteinG: 3, carbsG: 20, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Trà Lipton", categorySlug: "drinks", servingSize: "1 ly (250ml)", servingGrams: 250, calories: 5, proteinG: 0, carbsG: 1, fatG: 0, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Cà phê muối Huế", categorySlug: "drinks", servingSize: "1 ly (200ml)", servingGrams: 200, calories: 60, proteinG: 1, carbsG: 8, fatG: 3, mealTime: ["breakfast", "snack"] },
  { nameVi: "Kem dừa Hội An", categorySlug: "snacks", servingSize: "1 phần (150g)", servingGrams: 150, calories: 250, proteinG: 3, carbsG: 22, fatG: 17, mealTime: ["snack"] },
  { nameVi: "Sinh tố bơ", categorySlug: "drinks", servingSize: "1 ly (300ml)", servingGrams: 350, calories: 280, proteinG: 3, carbsG: 30, fatG: 16, mealTime: ["breakfast", "snack"] },
  { nameVi: "Bánh tráng cuốn thịt heo", categorySlug: "main-dish", servingSize: "1 dĩa (8 cuốn)", servingGrams: 250, calories: 320, proteinG: 18, carbsG: 35, fatG: 10, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh tráng trộn", categorySlug: "snacks", servingSize: "1 tô (200g)", servingGrams: 200, calories: 280, proteinG: 6, carbsG: 35, fatG: 12, mealTime: ["snack"] },
  { nameVi: "Bánh tráng nướng", categorySlug: "snacks", servingSize: "2 cái (100g)", servingGrams: 100, calories: 180, proteinG: 4, carbsG: 22, fatG: 8, mealTime: ["snack"] },
  { nameVi: "Hến xúc bánh tráng", categorySlug: "side-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 160, proteinG: 12, carbsG: 15, fatG: 5, mealTime: ["snack"] },
  { nameVi: "Hến nấu chua", categorySlug: "main-dish", servingSize: "1 tô (300g)", servingGrams: 300, calories: 180, proteinG: 12, carbsG: 22, fatG: 4, mealTime: ["lunch", "dinner"] },
  { nameVi: "Mít trộn", categorySlug: "side-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 180, proteinG: 2, carbsG: 35, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Rau càng cua luộc", categorySlug: "side-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 30, proteinG: 2, carbsG: 5, fatG: 0.5, mealTime: ["lunch", "dinner"] },
  { nameVi: "Rau đắng", categorySlug: "side-dish", servingSize: "1 phần (100g)", servingGrams: 100, calories: 25, proteinG: 2, carbsG: 4, fatG: 0.5, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cải xanh xào tỏi", categorySlug: "side-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 80, proteinG: 4, carbsG: 6, fatG: 5, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bông thiên lý xào", categorySlug: "side-dish", servingSize: "1 phần (150g)", servingGrams: 150, calories: 70, proteinG: 3, carbsG: 5, fatG: 4, mealTime: ["lunch", "dinner"] },
  { nameVi: "Nước mắm sả ớt", categorySlug: "side-dish", servingSize: "1 chén (30g)", servingGrams: 30, calories: 30, proteinG: 1, carbsG: 4, fatG: 1, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Mắm ruốc Huế", categorySlug: "side-dish", servingSize: "1 phần (20g)", servingGrams: 20, calories: 25, proteinG: 3, carbsG: 1, fatG: 1, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Bánh ít trần", categorySlug: "snacks", servingSize: "1 dĩa (4 cái)", servingGrams: 150, calories: 200, proteinG: 4, carbsG: 38, fatG: 4, mealTime: ["snack"] },
  { nameVi: "Bánh bò thốt nốt", categorySlug: "snacks", servingSize: "3 cái (100g)", servingGrams: 100, calories: 220, proteinG: 3, carbsG: 38, fatG: 6, mealTime: ["snack"] },
  { nameVi: "Bánh chuối hấp", categorySlug: "snacks", servingSize: "1 phần (150g)", servingGrams: 150, calories: 220, proteinG: 3, carbsG: 40, fatG: 5, mealTime: ["snack"] },
  { nameVi: "Cháo vịt", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 320, proteinG: 18, carbsG: 40, fatG: 8, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Cháo hến", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 250, proteinG: 12, carbsG: 38, fatG: 5, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Cháo tôm", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 280, proteinG: 14, carbsG: 40, fatG: 6, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Bánh căn", categorySlug: "snacks", servingSize: "1 dĩa (4 cái)", servingGrams: 150, calories: 240, proteinG: 8, carbsG: 30, fatG: 10, mealTime: ["snack"] },
  { nameVi: "Bánh xèo Huế", categorySlug: "main-dish", servingSize: "2 cái (200g)", servingGrams: 200, calories: 350, proteinG: 12, carbsG: 30, fatG: 20, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh khoái Huế", categorySlug: "main-dish", servingSize: "2 cái (200g)", servingGrams: 200, calories: 380, proteinG: 14, carbsG: 28, fatG: 24, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh ram ít", categorySlug: "snacks", servingSize: "1 dĩa (4 cái)", servingGrams: 150, calories: 240, proteinG: 5, carbsG: 32, fatG: 10, mealTime: ["snack"] },
  { nameVi: "Bánh đập", categorySlug: "snacks", servingSize: "2 cái (100g)", servingGrams: 100, calories: 200, proteinG: 4, carbsG: 28, fatG: 8, mealTime: ["snack"] },
  { nameVi: "Bánh cuốn thịt nướng", categorySlug: "main-dish", servingSize: "1 dĩa (300g)", servingGrams: 300, calories: 380, proteinG: 16, carbsG: 45, fatG: 14, mealTime: ["lunch", "dinner"] },
  { nameVi: "Bánh ướt cuốn tôm", categorySlug: "main-dish", servingSize: "1 dĩa (250g)", servingGrams: 250, calories: 300, proteinG: 14, carbsG: 38, fatG: 10, mealTime: ["lunch", "dinner"] },
  { nameVi: "Cháo lòng", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 380, proteinG: 20, carbsG: 38, fatG: 16, mealTime: ["breakfast", "lunch", "dinner"] },
  { nameVi: "Bún lòng heo", categorySlug: "main-dish", servingSize: "1 tô (400g)", servingGrams: 400, calories: 420, proteinG: 22, carbsG: 45, fatG: 16, mealTime: ["breakfast", "lunch"] },
  { nameVi: "Mực hấp gừng", categorySlug: "main-dish", servingSize: "1 phần (200g)", servingGrams: 200, calories: 160, proteinG: 22, carbsG: 3, fatG: 6, mealTime: ["lunch", "dinner", "snack"] },
]

export async function seedFoodsCentral(prisma: PrismaClient) {
  const region = await prisma.region.findUnique({ where: { code: "central" } })
  if (!region) throw new Error("Central region not found")

  for (const food of foods) {
    const category = await prisma.category.findUnique({ where: { slug: food.categorySlug } })
    if (!category) throw new Error(`Category ${food.categorySlug} not found`)

    await prisma.food.upsert({
      where: { id: food.nameVi },
      update: {
        nameVi: food.nameVi,
        regionId: region.id,
        categoryId: category.id,
        servingSize: food.servingSize,
        servingGrams: food.servingGrams,
        calories: food.calories,
        proteinG: food.proteinG,
        carbsG: food.carbsG,
        fatG: food.fatG,
        mealTime: food.mealTime,
        isVerified: false,
      },
      create: {
        id: food.nameVi,
        nameVi: food.nameVi,
        regionId: region.id,
        categoryId: category.id,
        servingSize: food.servingSize,
        servingGrams: food.servingGrams,
        calories: food.calories,
        proteinG: food.proteinG,
        carbsG: food.carbsG,
        fatG: food.fatG,
        mealTime: food.mealTime,
        isVerified: false,
      },
    })
  }
  console.log(`✅ Seeded ${foods.length} central dishes`)
}
