import { PrismaClient } from "../../src/generated/prisma"

const foods = [
  // === Phở ===
  {
    nameVi: "Phở bò tái",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 350,
    proteinG: 20,
    carbsG: 45,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Phở bò chín",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 360,
    proteinG: 22,
    carbsG: 45,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Phở gà",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 340,
    proteinG: 18,
    carbsG: 45,
    fatG: 9,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Phở cuốn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 200,
    calories: 280,
    proteinG: 12,
    carbsG: 35,
    fatG: 10,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Phở chiên phồng",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 đĩa",
    servingGrams: 250,
    calories: 380,
    proteinG: 14,
    carbsG: 40,
    fatG: 18,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Phở trộn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 300,
    calories: 350,
    proteinG: 15,
    carbsG: 42,
    fatG: 14,
    mealTime: ["lunch", "dinner"],
  },
  // === Bún ===
  {
    nameVi: "Bún chả Hà Nội",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 350,
    calories: 450,
    proteinG: 25,
    carbsG: 50,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Bún thang",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 22,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bún ốc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 320,
    proteinG: 15,
    carbsG: 48,
    fatG: 8,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bún đậu mắm tôm",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 350,
    calories: 420,
    proteinG: 20,
    carbsG: 45,
    fatG: 18,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Bún riêu cua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 380,
    proteinG: 20,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bún sườn chua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 400,
    proteinG: 22,
    carbsG: 50,
    fatG: 12,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Bún cá",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 360,
    proteinG: 18,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bún mọc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 370,
    proteinG: 20,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bún ngan",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 350,
    proteinG: 18,
    carbsG: 48,
    fatG: 9,
    mealTime: ["lunch", "dinner"],
  },
  // === Miến ===
  {
    nameVi: "Miến lươn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 350,
    proteinG: 18,
    carbsG: 42,
    fatG: 12,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Miến gà",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 330,
    proteinG: 16,
    carbsG: 42,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Miến trộn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 300,
    calories: 380,
    proteinG: 15,
    carbsG: 40,
    fatG: 16,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Miến cua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 320,
    proteinG: 15,
    carbsG: 42,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  // === Cháo ===
  {
    nameVi: "Cháo lòng",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 380,
    proteinG: 18,
    carbsG: 42,
    fatG: 15,
    mealTime: ["breakfast", "dinner", "snack"],
  },
  {
    nameVi: "Cháo gà",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 320,
    proteinG: 16,
    carbsG: 42,
    fatG: 10,
    mealTime: ["breakfast", "dinner", "snack"],
  },
  {
    nameVi: "Cháo trai",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 300,
    proteinG: 14,
    carbsG: 42,
    fatG: 8,
    mealTime: ["breakfast", "dinner", "snack"],
  },
  {
    nameVi: "Cháo sườn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 350,
    calories: 340,
    proteinG: 16,
    carbsG: 42,
    fatG: 12,
    mealTime: ["breakfast", "dinner", "snack"],
  },
  // === Bánh cuốn / Bánh ===
  {
    nameVi: "Bánh cuốn Thanh Trì",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 đĩa",
    servingGrams: 250,
    calories: 280,
    proteinG: 12,
    carbsG: 42,
    fatG: 8,
    mealTime: ["breakfast", "lunch", "snack"],
  },
  {
    nameVi: "Bánh tôm Hồ Tây",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 350,
    proteinG: 14,
    carbsG: 30,
    fatG: 20,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Bánh gối",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 100,
    calories: 220,
    proteinG: 10,
    carbsG: 22,
    fatG: 12,
    mealTime: ["snack"],
  },
  {
    nameVi: "Bánh bao",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 120,
    calories: 280,
    proteinG: 12,
    carbsG: 36,
    fatG: 10,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Bánh giầy",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 80,
    calories: 200,
    proteinG: 6,
    carbsG: 36,
    fatG: 4,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Bánh khúc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 100,
    calories: 220,
    proteinG: 6,
    carbsG: 38,
    fatG: 6,
    mealTime: ["breakfast", "snack"],
  },
  // === Xôi ===
  {
    nameVi: "Xôi mặn",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 300,
    calories: 420,
    proteinG: 16,
    carbsG: 60,
    fatG: 12,
    mealTime: ["breakfast", "lunch", "snack"],
  },
  {
    nameVi: "Xôi gấc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 250,
    calories: 380,
    proteinG: 8,
    carbsG: 60,
    fatG: 12,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Xôi lạc",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 250,
    calories: 400,
    proteinG: 12,
    carbsG: 58,
    fatG: 14,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Xôi xéo",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 250,
    calories: 420,
    proteinG: 10,
    carbsG: 60,
    fatG: 16,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Xôi vò",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 250,
    calories: 380,
    proteinG: 8,
    carbsG: 60,
    fatG: 12,
    mealTime: ["breakfast", "snack"],
  },
  // === Cốm ===
  {
    nameVi: "Cốm làng Vòng",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 suất",
    servingGrams: 100,
    calories: 180,
    proteinG: 6,
    carbsG: 34,
    fatG: 3,
    mealTime: ["snack"],
  },
  {
    nameVi: "Chả cốm",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 suất",
    servingGrams: 100,
    calories: 180,
    proteinG: 10,
    carbsG: 18,
    fatG: 8,
    mealTime: ["lunch", "dinner", "snack"],
  },
  // === Bánh mì ===
  {
    nameVi: "Bánh mì Hà Nội",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 200,
    calories: 350,
    proteinG: 14,
    carbsG: 48,
    fatG: 12,
    mealTime: ["breakfast", "lunch", "snack"],
  },
  {
    nameVi: "Bánh mì chảo",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 suất",
    servingGrams: 350,
    calories: 450,
    proteinG: 22,
    carbsG: 42,
    fatG: 22,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Bánh mì pate",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 cái",
    servingGrams: 200,
    calories: 380,
    proteinG: 16,
    carbsG: 46,
    fatG: 16,
    mealTime: ["breakfast", "lunch", "snack"],
  },
  // === Giò / Chả ===
  {
    nameVi: "Giò lụa",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "100g",
    servingGrams: 100,
    calories: 150,
    proteinG: 14,
    carbsG: 5,
    fatG: 8,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Giò thủ",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "100g",
    servingGrams: 100,
    calories: 200,
    proteinG: 14,
    carbsG: 4,
    fatG: 15,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Giò tai",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "100g",
    servingGrams: 100,
    calories: 180,
    proteinG: 14,
    carbsG: 5,
    fatG: 12,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Chả quế",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "100g",
    servingGrams: 100,
    calories: 220,
    proteinG: 16,
    carbsG: 6,
    fatG: 15,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Chả lợn",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "100g",
    servingGrams: 100,
    calories: 240,
    proteinG: 16,
    carbsG: 8,
    fatG: 17,
    mealTime: ["lunch", "dinner", "snack"],
  },
  // === Nem / Nộm ===
  {
    nameVi: "Nem rán (chả giò)",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 suất",
    servingGrams: 150,
    calories: 350,
    proteinG: 14,
    carbsG: 24,
    fatG: 22,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Nem cua bể",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 suất",
    servingGrams: 180,
    calories: 320,
    proteinG: 16,
    carbsG: 22,
    fatG: 18,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Nộm đu đủ",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 150,
    calories: 120,
    proteinG: 4,
    carbsG: 20,
    fatG: 4,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Nộm hoa chuối",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 150,
    calories: 110,
    proteinG: 4,
    carbsG: 18,
    fatG: 4,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Nộm sứa",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 150,
    calories: 100,
    proteinG: 8,
    carbsG: 10,
    fatG: 3,
    mealTime: ["lunch", "dinner", "snack"],
  },
  // === Canh ===
  {
    nameVi: "Canh cua mồng tơi",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 120,
    proteinG: 8,
    carbsG: 14,
    fatG: 4,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Canh cá thì là",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 140,
    proteinG: 12,
    carbsG: 8,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Canh chua tam thất",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 100,
    proteinG: 4,
    carbsG: 16,
    fatG: 2,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Canh bí đỏ",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 110,
    proteinG: 3,
    carbsG: 18,
    fatG: 4,
    mealTime: ["lunch", "dinner"],
  },
  // === Kho / Rang / Om ===
  {
    nameVi: "Cá kho làng Vũ Đại",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 350,
    proteinG: 30,
    carbsG: 10,
    fatG: 20,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Thịt kho tàu",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 450,
    proteinG: 28,
    carbsG: 15,
    fatG: 30,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Gà rang muối",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 380,
    proteinG: 30,
    carbsG: 5,
    fatG: 26,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Vịt om sấu",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 250,
    calories: 420,
    proteinG: 26,
    carbsG: 12,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
  },
  // === Ốc / Tôm / Hải sản ===
  {
    nameVi: "Ốc luộc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 suất",
    servingGrams: 200,
    calories: 150,
    proteinG: 18,
    carbsG: 6,
    fatG: 6,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Ốc xào dừa",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 220,
    proteinG: 16,
    carbsG: 10,
    fatG: 14,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Bề bề rang muối",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 250,
    proteinG: 22,
    carbsG: 5,
    fatG: 16,
    mealTime: ["lunch", "dinner", "snack"],
  },
  {
    nameVi: "Tôm rang thịt",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 280,
    proteinG: 24,
    carbsG: 8,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
  },
  // === Rau / Củ luộc & muối ===
  {
    nameVi: "Rau muống luộc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 60,
    proteinG: 5,
    carbsG: 8,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Su hào luộc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 50,
    proteinG: 3,
    carbsG: 10,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Bắp cải luộc",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 50,
    proteinG: 3,
    carbsG: 10,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Cà pháo muối",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 phần",
    servingGrams: 100,
    calories: 30,
    proteinG: 1,
    carbsG: 5,
    fatG: 1,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Dưa cải muối",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 phần",
    servingGrams: 100,
    calories: 25,
    proteinG: 1,
    carbsG: 4,
    fatG: 0.5,
    mealTime: ["lunch", "dinner"],
  },
  // === Bánh trôi / Bánh chay / Bánh cốm / Bánh phu thê ===
  {
    nameVi: "Bánh trôi",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 150,
    calories: 200,
    proteinG: 4,
    carbsG: 40,
    fatG: 4,
    mealTime: ["snack"],
  },
  {
    nameVi: "Bánh chay",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 150,
    calories: 210,
    proteinG: 4,
    carbsG: 42,
    fatG: 4,
    mealTime: ["snack"],
  },
  {
    nameVi: "Bánh cốm",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cái",
    servingGrams: 50,
    calories: 120,
    proteinG: 3,
    carbsG: 22,
    fatG: 3,
    mealTime: ["snack"],
  },
  {
    nameVi: "Bánh phu thê",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cái",
    servingGrams: 60,
    calories: 150,
    proteinG: 3,
    carbsG: 28,
    fatG: 4,
    mealTime: ["snack"],
  },
  // === Chè ===
  {
    nameVi: "Chè đậu đen",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 250,
    proteinG: 10,
    carbsG: 48,
    fatG: 3,
    mealTime: ["snack"],
  },
  {
    nameVi: "Chè đậu xanh",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 260,
    proteinG: 10,
    carbsG: 50,
    fatG: 3,
    mealTime: ["snack"],
  },
  {
    nameVi: "Chè cốm",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 240,
    proteinG: 6,
    carbsG: 48,
    fatG: 4,
    mealTime: ["snack"],
  },
  {
    nameVi: "Chè sen",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 230,
    proteinG: 6,
    carbsG: 46,
    fatG: 3,
    mealTime: ["snack"],
  },
  {
    nameVi: "Chè khoai môn",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 bát",
    servingGrams: 250,
    calories: 270,
    proteinG: 4,
    carbsG: 52,
    fatG: 6,
    mealTime: ["snack"],
  },
  // === Trà / Nước giải khát ===
  {
    nameVi: "Trà sen Tây Hồ",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 5,
    proteinG: 0,
    carbsG: 1,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Trà đá vỉa hè",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 300,
    calories: 3,
    proteinG: 0,
    carbsG: 0.5,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Nước sấu dầm",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 80,
    proteinG: 0.5,
    carbsG: 18,
    fatG: 1,
    mealTime: ["snack"],
  },
  {
    nameVi: "Nước mơ",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 90,
    proteinG: 0.5,
    carbsG: 20,
    fatG: 0.5,
    mealTime: ["snack"],
  },
  {
    nameVi: "Nước vối",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 3,
    proteinG: 0,
    carbsG: 0.5,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
  },
  // === Đồ uống khác ===
  {
    nameVi: "Bia hơi Hà Nội",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 cốc",
    servingGrams: 330,
    calories: 130,
    proteinG: 1,
    carbsG: 10,
    fatG: 0,
    mealTime: ["snack"],
  },
  {
    nameVi: "Cà phê trứng",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 cốc",
    servingGrams: 150,
    calories: 250,
    proteinG: 6,
    carbsG: 20,
    fatG: 16,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Cà phê sữa đá",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 cốc",
    servingGrams: 200,
    calories: 150,
    proteinG: 4,
    carbsG: 20,
    fatG: 6,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Sữa chua mít",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 hộp",
    servingGrams: 200,
    calories: 220,
    proteinG: 6,
    carbsG: 36,
    fatG: 6,
    mealTime: ["snack"],
  },
  // === Chim / Bồ câu / Chả chìa / Măng ===
  {
    nameVi: "Chim quay",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 200,
    calories: 380,
    proteinG: 28,
    carbsG: 4,
    fatG: 28,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Bồ câu quay",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 con",
    servingGrams: 200,
    calories: 360,
    proteinG: 30,
    carbsG: 4,
    fatG: 24,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Chả chìa",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 phần",
    servingGrams: 150,
    calories: 280,
    proteinG: 18,
    carbsG: 10,
    fatG: 18,
    mealTime: ["lunch", "dinner"],
  },
  {
    nameVi: "Măng tươi xào",
    regionCode: "northern",
    categorySlug: "side-dish",
    servingSize: "1 đĩa",
    servingGrams: 200,
    calories: 120,
    proteinG: 4,
    carbsG: 14,
    fatG: 6,
    mealTime: ["lunch", "dinner"],
  },
  // === Rượu ===
  {
    nameVi: "Rượu nếp",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 chén",
    servingGrams: 50,
    calories: 120,
    proteinG: 0.5,
    carbsG: 6,
    fatG: 0,
    mealTime: ["snack"],
  },
  {
    nameVi: "Rượu gạo",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 chén",
    servingGrams: 50,
    calories: 110,
    proteinG: 0,
    carbsG: 1,
    fatG: 0,
    mealTime: ["snack"],
  },
  {
    nameVi: "Rượu sim",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 chén",
    servingGrams: 50,
    calories: 100,
    proteinG: 0,
    carbsG: 8,
    fatG: 0,
    mealTime: ["snack"],
  },
  // === Additional Northern dishes ===
  {
    nameVi: "Bánh đa cua",
    regionCode: "northern",
    categorySlug: "main-dish",
    servingSize: "1 tô",
    servingGrams: 400,
    calories: 370,
    proteinG: 20,
    carbsG: 48,
    fatG: 10,
    mealTime: ["breakfast", "lunch", "dinner"],
  },
  {
    nameVi: "Bánh tẻ",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cái",
    servingGrams: 80,
    calories: 160,
    proteinG: 4,
    carbsG: 30,
    fatG: 3,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Cà phê đen đá",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 cốc",
    servingGrams: 200,
    calories: 5,
    proteinG: 0.5,
    carbsG: 0,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Ô mai sấu",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phần",
    servingGrams: 50,
    calories: 100,
    proteinG: 1,
    carbsG: 22,
    fatG: 1,
    mealTime: ["snack"],
  },
  {
    nameVi: "Nước chanh",
    regionCode: "northern",
    categorySlug: "drinks",
    servingSize: "1 ly",
    servingGrams: 250,
    calories: 60,
    proteinG: 0.2,
    carbsG: 14,
    fatG: 0,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Kẹo lạc",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phần",
    servingGrams: 50,
    calories: 240,
    proteinG: 8,
    carbsG: 28,
    fatG: 12,
    mealTime: ["snack"],
  },
  {
    nameVi: "Bánh đúc lạc",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 suất",
    servingGrams: 150,
    calories: 200,
    proteinG: 6,
    carbsG: 34,
    fatG: 6,
    mealTime: ["breakfast", "snack"],
  },
  {
    nameVi: "Bánh rán",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 cái",
    servingGrams: 80,
    calories: 200,
    proteinG: 4,
    carbsG: 28,
    fatG: 10,
    mealTime: ["snack"],
  },
  {
    nameVi: "Mít sấy",
    regionCode: "northern",
    categorySlug: "snacks",
    servingSize: "1 phần",
    servingGrams: 50,
    calories: 150,
    proteinG: 2,
    carbsG: 34,
    fatG: 1,
    mealTime: ["snack"],
  },
]

export async function seedFoodsNorthern(prisma: PrismaClient) {
  const region = await prisma.region.findUnique({ where: { code: "northern" } })
  if (!region) throw new Error("Northern region not found")

  for (const food of foods) {
    const category = await prisma.category.findUnique({ where: { slug: food.categorySlug } })
    if (!category) throw new Error(`Category ${food.categorySlug} not found`)

    await prisma.food.upsert({
      where: { id: food.nameVi },
      update: {
        nameVi: food.nameVi,
        regionId: region.id,
        categoryId: category.id,
        servingSize: food.servingSize,
        servingGrams: food.servingGrams,
        calories: food.calories,
        proteinG: food.proteinG,
        carbsG: food.carbsG,
        fatG: food.fatG,
        mealTime: food.mealTime,
        isVerified: false,
      },
      create: {
        id: food.nameVi,
        nameVi: food.nameVi,
        regionId: region.id,
        categoryId: category.id,
        servingSize: food.servingSize,
        servingGrams: food.servingGrams,
        calories: food.calories,
        proteinG: food.proteinG,
        carbsG: food.carbsG,
        fatG: food.fatG,
        mealTime: food.mealTime,
        isVerified: false,
      },
    })
  }
  console.log(`✅ Seeded ${foods.length} northern dishes`)
}
